import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
function load(path,dependencies={}){const m={exports:{}};new Function('exports','module','require',ts.transpileModule(fs.readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(m.exports,m,n=>dependencies[n]);return m.exports}
const analytics=load('../lib/analytics.ts');const {validDocument,validAnnouncement,documentText,filterAnnouncements}=load('../lib/announcement.ts',{'./analytics':analytics,'./announcement-poll':load('../lib/announcement-poll.ts')});const {deadline,expired,validTrashRequest}=load('../lib/trash.ts');
const doc={type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Briefing',marks:[{type:'bold'}]}]},{type:'table',content:[{type:'tableRow',content:[{type:'tableCell',content:[{type:'paragraph',content:[{type:'text',text:'Friday'}]}]}]}]}]};
test('announcement accepts formatted text and tables but requires a title',()=>{assert.equal(validDocument(doc),true);assert.equal(documentText(doc),'Briefing\nFriday');assert.equal(validAnnouncement({title:'Briefing',subtitle:'',body:doc}),true);assert.equal(validAnnouncement({title:' ',subtitle:'',body:doc}),false);assert.equal(validAnnouncement({title:'Briefing',subtitle:'',body:{type:'doc',content:[{type:'paragraph'}]}}),true)});
test('announcement rejects unsafe unknown nodes, unsupported marks and excessive nesting',()=>{assert.equal(validDocument({type:'doc',content:[{type:'script',text:'alert(1)'}]}),false);assert.equal(validDocument({type:'doc',content:[{type:'text',text:'x',marks:[{type:'link',attrs:{href:'javascript:alert(1)'}}]}]}),false);let nested={type:'text',text:'x'};for(let i=0;i<20;i++)nested={type:'paragraph',content:[nested]};assert.equal(validDocument({type:'doc',content:[nested]}),false)});
test('announcement date filters include WIB date boundaries and omit trash',()=>{const rows=[{id:'1',title:'Briefing',subtitle:'',created_by_name:'A',created_at:'2026-10-08T17:00:00Z'},{id:'2',title:'Other',subtitle:'',created_by_name:'A',created_at:'2026-10-09T17:00:00Z'},{id:'3',title:'Briefing',subtitle:'',created_by_name:'A',created_at:'2026-10-09T01:00:00Z',deleted_at:'x'}];assert.deepEqual(filterAnnouncements(rows,'','day','','',new Date('2026-10-09T02:00:00Z')).map(r=>r.id),['1']);assert.deepEqual(filterAnnouncements(rows,' briefing ','range','2026-10-09','2026-10-09').map(r=>r.id),['1'])});
test('trash deadline is exactly 30 days and expires inclusively',()=>{const end=deadline('2026-10-09T03:00:00Z');assert.equal(end,'2026-11-08T03:00:00.000Z');assert.equal(expired({purge_after:end},Date.parse(end)-1),false);assert.equal(expired({purge_after:end},Date.parse(end)),true)});
test('trash requests reject duplicates, unknown modules, invalid actions and identifiers',()=>{const item={id:'94a54084-416a-4dac-ab7f-955d0f35a76b',kind:'patient_consent'};assert.equal(validTrashRequest({action:'restore',items:[item]}),true);for(const b of [{action:'delete',items:[item,item]},{action:'delete',items:[{...item,kind:'profiles'}]},{action:'delete',items:[{...item,id:'1'}]},{action:'update',items:[item]},{action:'delete',items:[]}])assert.equal(validTrashRequest(b),false)});

test('pinned announcements appear first and retain newest-first order within each group',()=>{const rows=[{id:'new',title:'New',created_at:'2026-10-09T10:00:00Z'},{id:'pinned-old',title:'Pinned old',is_pinned:true,created_at:'2026-10-01T10:00:00Z'},{id:'pinned-new',title:'Pinned new',is_pinned:true,created_at:'2026-10-08T10:00:00Z'}];assert.deepEqual(filterAnnouncements(rows,'','all','','').map(r=>r.id),['pinned-new','pinned-old','new']);rows[1].is_pinned=false;rows[2].is_pinned=false;assert.deepEqual(filterAnnouncements(rows,'','all','','').map(r=>r.id),['new','pinned-new','pinned-old'])});
