import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const compiled=ts.transpileModule(fs.readFileSync(new URL('../lib/case-assistant.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const module={exports:{}};new Function('exports','module',compiled)(module.exports,module);const {assistantFields,parseCaseResult,applyAssistant,formatRpGcs,normalizeRpVitals}=module.exports;
const fixture=()=>({title:'RP injury',category:'minor',fields:Object.fromEntries(assistantFields.map(k=>[k,k==='Type of Anesthesia'?'local':'RP example'])),instruments:['RP instrument'],roleplay:['/me prepares'],discharge:['RP care'],assumptions:['Simulated']});
test('assistant rejects incomplete results and invalid anesthesia',()=>{const value=fixture();assert.equal(parseCaseResult(JSON.stringify(value)).title,'RP injury');delete value.fields.Anamnesis;assert.throws(()=>parseCaseResult(JSON.stringify(value)));const invalid=fixture();invalid.fields['Type of Anesthesia']='unknown';assert.throws(()=>parseCaseResult(JSON.stringify(invalid)))});
test('assistant transfer retains patient details and resets stale preview',()=>{const d=applyAssistant({fields:{'Patient Name':'RP person'},times:{ANAMNESIS:'WIB'},category:'major',caseText:'old',preview:'old',previewHtml:'old',richFields:{Anamnesis:'old'}},{caseText:'New RP case',result:fixture()});assert.equal(d.fields['Patient Name'],'RP person');assert.equal(d.fields.Anamnesis,'RP example');assert.equal(d.times.ANAMNESIS,'WIB');assert.equal(d.preview,'');assert.equal(d.previewHtml,undefined);assert.deepEqual(d.richFields,{})});

test('discharge suggestions transfer into follow up without repeating existing lines',()=>{const result=fixture();result.fields['Follow Up Care']='RP care';result.discharge=['RP care','Return for review'];const draft=applyAssistant({fields:{},times:{},category:'minor',caseText:'',preview:''},{caseText:'case',result});assert.equal((draft.fields['Follow Up Care'].match(/RP care/g)||[]).length,1);assert.ok(draft.fields['Follow Up Care'].includes('Return for review'))});

test('RP GCS totals are computed from E V M with custom consciousness labels',()=>{for(const [input,label,total] of [['E1 V1 M1','Coma',3],['E1 V1 M2','Semi-coma',4],['E1 V2 M3','Sopor',6],['E2 V3 M4','Somnolen',9],['E3 V3 M5','Delirium',11],['E3 V4 M6','Apatis',13],['E4 V5 M6','Composmentis',15]]){const text=formatRpGcs(input);assert.ok(text.includes(`${total}/15`));assert.ok(text.includes(label));assert.ok(text.includes('Eye:'));assert.ok(text.includes('Verbal:'));assert.ok(text.includes('Motorik:'))}assert.equal(formatRpGcs('15/15'),'15/15');assert.equal(normalizeRpVitals('Before Surgery — BP','120/80 (simulated)'),'120/80')});
