import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
function load(path){const code=ts.transpileModule(fs.readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const m={exports:{}};new Function('exports','module',code)(m.exports,m);return m.exports}
const {validConsultation,mentionRecipients,validCancellationReason}=load('../lib/consultation.ts');const {syncConsentLinks,matchingConsentLinks}=load('../lib/report-consent.ts');
const input={name:'Patient',dob:'',date:'2026-10-10',contact:'',job:'',complaint:'Follow up',notes:'',mentions:{users:[],roles:[],divisions:[]}};
test('consultation accepts optional fields but rejects invalid dates and missing essentials',()=>{assert.equal(validConsultation(input),true);for(const patch of [{name:''},{complaint:''},{date:'2026-02-30'},{dob:'invalid'},{mentions:{users:[],roles:[],divisions:['Unknown']}}])assert.equal(validConsultation({...input,...patch}),false)});
test('mention union reaches role, division and named users without duplicate recipients',()=>{assert.deepEqual(mentionRecipients({users:['a'],roles:['Specialist'],divisions:['Medical Service']},[{id:'a',role:'Specialist',division:'Medical Service'},{id:'b',role:'Specialist',division:'Fire Department'},{id:'c',role:'Member',division:'Other'}]),['a','b'])});
test('adding and replacing consent links retains edited report text and formatting',()=>{const link={id:'1',token:'abc',name:'Patient'};const draft={preview:'Custom edited report',previewHtml:'<p><strong>Custom edited report</strong></p>'};const attached=syncConsentLinks(draft,[link]);assert.match(attached.preview,/Custom edited report/);assert.match(attached.previewHtml,/<strong>/);assert.match(attached.preview,/\/share\/consent\/abc/);const removed=syncConsentLinks(attached,[]);assert.equal(removed.preview,'Custom edited report');assert.equal(removed.previewHtml,draft.previewHtml)});

test('automatic consent matching uses full normalized name and excludes deleted or unrelated patients',()=>{const rows=[{id:'a',share_token:'a-token',created_at:'2026-10-08',data:{patientName:' Adrian  Carter '}},{id:'b',share_token:'b-token',created_at:'2026-10-09',data:{patientName:'ADRIAN CARTER'}},{id:'c',share_token:'c-token',data:{patientName:'Adrian Carter Jr'}},{id:'d',share_token:'d-token',deleted_at:'2026-10-09',data:{patientName:'Adrian Carter'}}];assert.deepEqual(matchingConsentLinks('adrian carter',rows).map(l=>l.id),['b','a']);assert.deepEqual(matchingConsentLinks('',rows),[]);assert.deepEqual(matchingConsentLinks('Adrian',rows),[])});

test('cancellation requires a nonblank bounded reason',()=>{assert.equal(validCancellationReason('Patient cannot attend'),true);for(const value of ['', '   ',null,'x'.repeat(2001)])assert.equal(validCancellationReason(value),false)});
