import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const attachmentSource=ts.transpileModule(readFileSync(new URL('../lib/fire-attachments.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022}}).outputText;
const source=ts.transpileModule(readFileSync(new URL('../lib/fire-report.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022}}).outputText.replace("'./fire-attachments'",`'data:text/javascript;base64,${Buffer.from(attachmentSource).toString('base64')}'`);
const {freshFireDraft,validFireDraft,fireReportText}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const complete=()=>({...freshFireDraft('Sam Carter','Captain'),location:'Vinewood',incidentAt:'09/10/2026 18:30:00 GMT+7',reportDate:'09/10/2026',chronology:'Api terlihat di bangunan.',actions:'Evakuasi dan pemadaman.',damage:'Satu bangunan.',cause:'Korsleting.',closing:'Area diamankan.',commanderBadge:'FD-001',civilians:2,locals:1});
test('Big Fire follows the supplied document order and distinguishes emergency from resolved',()=>{const d=complete();assert.equal(validFireDraft(d),true);const text=fireReportText(d);for(const line of ['LAPORAN KEJADIAN KEBAKARAN Vinewood','Tanggal Kejadian: 09/10/2026','Waktu Kejadian: 18:30:00 GMT+7','Jenis Kejadian: Kebakaran','Status: Penanganan Darurat','Korban: 2 civilian | 1 warga lokal','Incident Commander: (FD-001) Sam Carter','Jabatan: Captain'])assert.ok(text.includes(line));assert.ok(text.indexOf('Kronologi Kejadian')<text.indexOf('Tindakan yang Dilakukan'));assert.ok(text.indexOf('Penyebab Kebakaran')<text.indexOf('Penutup'));assert.match(fireReportText({...d,status:'resolved'}),/Status: Teratasi/)});
test('rejects incomplete reports, impossible dates and invalid victim counts',()=>{for(const patch of [{location:''},{chronology:' '},{commanderBadge:''},{reportDate:'31/02/2026'},{incidentAt:'09/10/2026 25:00:00 GMT+7'},{civilians:-1},{locals:1.5},{status:'paid'},{rich:{actions:{}}}])assert.equal(validFireDraft({...complete(),...patch}),false);assert.equal(validFireDraft(freshFireDraft()),false)});

test('compact section spacing and multiple personnel are retained in document text',()=>{const d={...complete(),commanderPosition:'Captain, Lieutenant',personnel:[{id:'a',name:'Jamie',badge:'123'},{id:'b',name:'Alex',badge:''}]};assert.equal(validFireDraft(d),true);const text=fireReportText(d);assert.ok(text.includes('Kronologi Kejadian\nApi'));assert.ok(text.includes('Penutup\nArea'));assert.ok(text.includes('Personil: (123) Jamie, (-) Alex'));assert.equal(validFireDraft({...d,personnel:[{id:'a',name:123,badge:''}]}),false)});

test('FD attachments accept safe links and video metadata, reject unsafe or oversized entries',async()=>{const {validFireAttachments,videoFileType}=await import(`data:text/javascript;base64,${Buffer.from(attachmentSource).toString('base64')}`);assert.equal(validFireAttachments([{id:'link',kind:'link',name:'Evidence',url:'https://example.com/video'}]),true);assert.equal(validFireAttachments([{id:'link',kind:'link',name:'Evidence',url:'javascript:alert(1)'}]),false);const file={id:'v',kind:'video',name:'Fire.mp4',path:'94a54084-416a-4dac-ab7f-955d0f35a76b/aa5f56fb-6d36-4165-996f-e46aeab0a17d.mp4',size:1000};assert.equal(validFireAttachments([file]),true);assert.equal(validFireAttachments([{...file,size:5000000}]),false);assert.equal(videoFileType(new Uint8Array([0,0,0,20,102,116,121,112,105,115,111,109])).kind,'video')});
