import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
function load(path,deps={}){const m={exports:{}};new Function('exports','module','require',ts.transpileModule(fs.readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(m.exports,m,n=>deps[n]);return m.exports}
const {normalizeMemberEdit,memberEditError,assignmentUnchanged}=load('../lib/member-edit.ts',{'./member-options':load('../lib/member-options.ts')});
const payload={name:'Leopold De Montegard',role:'SAHD',division:'Medical Service',position:'Chief',teams:['Human Resource'],access:'Admin'};
test('Chief with HR assignment can receive Admin access',()=>{assert.equal(memberEditError(normalizeMemberEdit(payload),false),null)});
test('form whitespace and comma spacing normalize before assignment validation',()=>{const data=normalizeMemberEdit({...payload,role:' SAHD ',position:'Doctor Resident,Chief ',teams:['Human Resource '],access:' Admin '});assert.equal(data.position,'Doctor Resident, Chief');assert.equal(memberEditError(data,false),null)});
test('invalid access and cross-division positions remain rejected',()=>{assert.match(memberEditError(normalizeMemberEdit({...payload,access:'Superadmin'}),false),/akses/);assert.match(memberEditError(normalizeMemberEdit({...payload,position:'Captain'}),false),/jabatan/)});

test('access-only changes preserve assignments and any assignment edit uses the full edit flow',()=>{const member={name:payload.name,division:payload.division,position:payload.position,teams:payload.teams};assert.equal(assignmentUnchanged(member,member),true);assert.equal(assignmentUnchanged({...member,position:'Director'},member),false);assert.equal(assignmentUnchanged({...member,teams:[]},member),false);assert.equal(assignmentUnchanged({...member,name:'Other'},member),false)});
test('access-only API uses saved assignment rather than stale form values',async()=>{let sent;let reads=0;const client={auth:{getUser:async()=>({data:{user:{id:'94a54084-416a-4dac-ab7f-955d0f35a76b'}}})},from:()=>({select:()=>({eq:()=>({single:async()=>({data:++reads===1?{access_role:'Superadmin',is_active:true}:{display_name:payload.name,role:'SAHD',division:'Medical Service',job_title:'Chief',teams:['Human Resource'],access_role:'Member'}})})})}),rpc:async(_,args)=>{sent=args;return {error:null}}};const {PATCH}=load('../app/api/members/route.ts',{'@/lib/supabase/server':{serverClient:async()=>client,validOrigin:()=>true},'@/lib/member-edit':{normalizeMemberEdit,memberEditError}});const response=await PATCH(new Request('https://example.com/api/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'aa5f56fb-6d36-4165-996f-e46aeab0a17d',remove:false,accessOnly:true,access:'Admin',division:'stale',position:'stale',teams:[]})}));assert.equal(response.status,200);assert.equal(sent.new_access,'Admin');assert.equal(sent.new_division,'Medical Service');assert.equal(sent.new_position,'Chief');assert.deepEqual(sent.new_teams,['Human Resource'])});
