'use client';
import {LocalizedView} from './localized-view';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {ShieldCheck,Users,Save,Info} from 'lucide-react';
import type {Profile} from '@/lib/portal-data';
import {Button} from '@/components/ui/button';
import {ReportSelect} from './report-fields';
import {divisions,organizationRoles,memberTeams,positions} from '@/lib/member-options';
import {useFeedbackState} from '@/components/runtime/feedback-toast';
export default function AdminForm({members,demo=false}:{members:Profile[];demo?:boolean}){
 const router=useRouter();const [id,setId]=useState(''),[role,setRole]=useState('SAHD'),[division,setDivision]=useState(''),[position,setPosition]=useState(''),[teams,setTeams]=useState<string[]>([]),[message,setMessage]=useFeedbackState('', 'notice'),[error,setError]=useFeedbackState(''),[busy,setBusy]=useState(false);
 const selected=members.find(member=>member.id===id),items=(values:readonly string[])=>values.map(value=>({value,label:value}));
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');if(!id){setError('Pilih anggota yang ingin diperbarui.');document.getElementById('admin-member')?.focus();return}setBusy(true);try{if(demo)throw new Error('Demo hanya untuk preview. Masuk dengan akun admin untuk menyimpan penugasan.');const res=await fetch('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,role,division:division||null,position:position||null,teams})});if(!res.ok)throw new Error((await res.json()).error);setMessage('Assignment tersimpan.');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Assignment gagal.')}finally{setBusy(false)}}
 function chooseMember(value:string){setId(value==='none'?'':value);const member=members.find(m=>m.id===value);setRole(organizationRoles.some(r=>r===member?.role)?member!.role:'SAHD');setDivision(divisions.some(d=>d===member?.division)?member!.division:'');setPosition(member?.position||'');setTeams(member?.teams||[]);setError('');setMessage('')}
 return <LocalizedView><div className="admin-page"><div className="page-heading"><div><p className="eyebrow">SAHD · ADMINISTRATION</p><h1>Admin Panel</h1><p className="muted">Kelola penugasan organisasi anggota. Setiap perubahan dicatat dalam audit.</p></div><span className="admin-heading-icon"><ShieldCheck size={26}/></span></div><form onSubmit={submit} className="panel admin-assignment-form"><div className="admin-section-heading"><Users size={20}/><div><h2>Member Assignment</h2><p className="muted">Pilih anggota, lalu sesuaikan divisi, jabatan, dan team.</p></div></div><div className="field"><label htmlFor="admin-member">Member <span aria-hidden="true">*</span></label><ReportSelect id="admin-member" label="Member" value={id||'none'} items={[{value:'none',label:'Pilih Anggota'},...members.map(m=>({value:m.id,label:m.name}))]} onChange={chooseMember}/></div>{selected&&<div className="admin-member-summary"><b data-no-translate>{selected.name}</b><span className="badge">{selected.accessRole||'Member'}</span></div>}<div className="admin-field-grid"><div className="field"><label htmlFor="admin-role">Role</label><ReportSelect id="admin-role" label="Role" value={role} items={items(organizationRoles)} onChange={setRole}/></div><div className="field"><label htmlFor="admin-division">Division</label><ReportSelect id="admin-division" label="Division" value={division||'none'} items={[{value:'none',label:'Belum Ditentukan'},...items(divisions)]} onChange={value=>{setDivision(value==='none'?'':value);setPosition('Trainee')}}/></div><div className="field"><label htmlFor="admin-position">Position / Jabatan</label><ReportSelect id="admin-position" label="Position / Jabatan" value={position||'none'} items={[{value:'none',label:'Belum Ditentukan'},...items(positions[division]||['Trainee'])]} onChange={value=>setPosition(value==='none'?'':value)}/><small className="muted">Pilihan jabatan mengikuti divisi yang dipilih.</small></div></div><fieldset className="admin-team-field"><legend>Team</legend><p className="muted">Opsional. Anda dapat memilih lebih dari satu team.</p><div className="settings-teams">{memberTeams.map(team=><label key={team}><input type="checkbox" checked={teams.includes(team)} onChange={e=>setTeams(previous=>e.target.checked?[...previous,team]:previous.filter(t=>t!==team))}/>{team}</label>)}</div></fieldset><div className="admin-permission-note"><Info size={18}/><p>Form ini mengubah penugasan organisasi. Status akses Superadmin tetap dipertahankan.</p></div><div className="admin-form-footer"><Button className="admin-save-button" type="submit" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save Assignment'}</Button></div>{error&&<p className="module-error">{error}</p>}{message&&<p className="muted text-xs">{message}</p>}</form></div></LocalizedView>;
}
