'use client';
import {LocalizedView} from '@/components/portal/localized-view';

import {useEditor,EditorContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {TextStyleKit} from '@tiptap/extension-text-style';
import {TableKit} from '@tiptap/extension-table';
import TextAlign from '@tiptap/extension-text-align';
import {Bold,Italic,Underline,List,ListOrdered,Table2,Undo,Redo,AlignLeft,AlignCenter,AlignRight,Minus,Trash2,Plus} from 'lucide-react';
import type {RichNode} from '@/lib/announcement';
export default function AnnouncementEditor({value,onChange}:{value:RichNode;onChange:(v:RichNode)=>void}){
 const editor=useEditor({extensions:[StarterKit.configure({link:false}),TextStyleKit,TableKit,TextAlign.configure({types:['heading','paragraph']})],immediatelyRender:false,content:value,editorProps:{attributes:{role:'textbox','aria-label':'Announcement content','aria-multiline':'true'}},onUpdate:({editor})=>onChange(editor.getJSON() as RichNode)});
 const actions=[['Bold',Bold,()=>editor?.chain().focus().toggleBold().run()],['Italic',Italic,()=>editor?.chain().focus().toggleItalic().run()],['Underline',Underline,()=>editor?.chain().focus().toggleUnderline().run()],['Bullet list',List,()=>editor?.chain().focus().toggleBulletList().run()],['Numbered list',ListOrdered,()=>editor?.chain().focus().toggleOrderedList().run()],['Align left',AlignLeft,()=>editor?.chain().focus().setTextAlign('left').run()],['Align center',AlignCenter,()=>editor?.chain().focus().setTextAlign('center').run()],['Align right',AlignRight,()=>editor?.chain().focus().setTextAlign('right').run()],['Insert table',Table2,()=>editor?.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run()],['Divider',Minus,()=>editor?.chain().focus().setHorizontalRule().run()],['Undo',Undo,()=>editor?.chain().focus().undo().run()],['Redo',Redo,()=>editor?.chain().focus().redo().run()]] as const;
 return <LocalizedView>{<div className="report-rich-editor announcement-editor"><div className="report-editor-toolbar" role="toolbar" aria-label="Announcement formatting"><select aria-label="Font family" onChange={e=>editor?.chain().focus().setFontFamily(e.target.value).run()}>{['Arial','Georgia','Times New Roman','Courier New'].map(f=><option key={f}>{f}</option>)}</select><select aria-label="Font size" defaultValue="16px" onChange={e=>editor?.chain().focus().setFontSize(e.target.value).run()}>{['12px','14px','16px','18px','24px','32px'].map(f=><option key={f}>{f}</option>)}</select><input type="color" aria-label="Text color" onChange={e=>editor?.chain().focus().setColor(e.target.value).run()}/>{actions.map(([name,Icon,act])=><button key={name} type="button" title={name} aria-label={name} onClick={act}><Icon size={16}/></button>)}{editor?.isActive('table')&&<><button type="button" aria-label="Add table row" title="Add table row" onClick={()=>editor.chain().focus().addRowAfter().run()}><Plus size={16}/></button><button type="button" aria-label="Add table column" title="Add table column" onClick={()=>editor.chain().focus().addColumnAfter().run()}><Table2 size={16}/></button><button type="button" aria-label="Delete table" title="Delete table" onClick={()=>editor.chain().focus().deleteTable().run()}><Trash2 size={16}/></button></>}</div><EditorContent editor={editor}/></div>}</LocalizedView>
}
