'use client';
import {useFeedbackState} from '@/components/runtime/feedback-toast';
import {LocalizedView} from './localized-view';
import {useState} from 'react';import {Paperclip,Link as LinkIcon,Trash2,ExternalLink} from 'lucide-react';
import {Button} from '@/components/animate-ui/components/buttons/button';import {usePortal} from './provider';
import {safeAttachmentLink,attachmentLimit,type AnnouncementAttachment} from '@/lib/announcement-attachments';
export function AnnouncementAttachments({value=[],onChange,onBusy}:{value?:AnnouncementAttachment[];onChange?:(items:AnnouncementAttachment[])=>void;onBusy?:(busy:boolean)=>void}){
 const {mode}=usePortal(),[busy,setBusy]=useState(false),[url,setUrl]=useState(''),[name,setName]=useState(''),[error,setError]=useFeedbackState('');
 async function upload(files:File[]){if(files.length+value.length>20){setError('Maksimal 20 attachment.');return}setBusy(true);onBusy?.(true);setError('');const added:AnnouncementAttachment[]=[];try{for(const file of files){if(!file.size||file.size>attachmentLimit)throw Error('File maksimal 4 MB.');if(!['image/png','image/jpeg','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain','text/csv'].includes(file.type))throw Error('Gunakan PNG, JPG, WebP, PDF, DOCX, TXT, atau CSV.');if(mode==='demo'){if(file.size>2*1024*1024)throw Error('File demo maksimal 2 MB agar dapat disimpan di browser.');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('File gagal dibaca.'));reader.readAsDataURL(file)});added.push({id:crypto.randomUUID(),kind:file.type.startsWith('image/')?'image':'file',name:file.name,url:data,size:file.size})}else{const form=new FormData();form.set('file',file);const response=await fetch('/api/announcements/attachments',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(data.error);added.push(data.attachment)}}}catch(e){setError(e instanceof Error?e.message:'Upload gagal.')}finally{if(added.length)onChange?.([...value,...added]);setBusy(false);onBusy?.(false)}}
 return <LocalizedView><section className="announcement-attachments"><h3>Attachments</h3>{onChange&&<><label className="attachment-upload"><Paperclip size={17}/>{busy?'Uploading…':'Add files or images'}<input aria-label="Upload announcement attachments" type="file" multiple disabled={busy||value.length>=20} accept=".png,.jpg,.jpeg,.webp,.pdf,.docx,.txt,.csv" onChange={e=>{void upload(Array.from(e.target.files||[]));e.target.value=''}}/></label><p className="muted text-xs">PNG, JPG, WebP, PDF, DOCX, TXT, CSV · 4 MB / file · 20 attachments</p><div className="attachment-link-fields"><input aria-label="Attachment link label" placeholder="Link label (optional)" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/><input aria-label="Attachment URL" placeholder="https://…" type="url" value={url} maxLength={2000} onChange={e=>setUrl(e.target.value)}/><Button type="button" variant="outline" disabled={busy||!url.trim()||value.length>=20} onClick={()=>{const href=safeAttachmentLink(url.trim());if(!href){setError('Gunakan link HTTP atau HTTPS yang valid.');return}onChange([...value,{id:crypto.randomUUID(),kind:'link',name:name.trim()||new URL(href).hostname,url:href}]);setUrl('');setName('');setError('')}}><LinkIcon size={15}/>Add link</Button></div></>}{error&&<p role="alert" className="module-error">{error}</p>}<div className="announcement-attachment-list">{value.map(a=><div className="announcement-attachment" key={a.id}>{a.kind==='image'&&a.url&&<a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.name}/></a>}<div><a href={a.url} target="_blank" rel="noreferrer" download={a.kind==='file'?a.name:undefined}><span data-no-translate>{a.name}</span><ExternalLink size={13}/></a>{a.size&&<small className="muted">{a.size<1024?`${a.size} B`:`${(a.size/1024).toFixed(0)} KB`}</small>}</div>{onChange&&<Button type="button" variant="ghost" size="icon" disabled={busy} aria-label={`Remove attachment ${a.name}`} onClick={()=>onChange(value.filter(x=>x.id!==a.id))}><Trash2 size={15}/></Button>}</div>)}</div>{!onChange&&!value.length&&<p className="muted">No attachments.</p>}</section></LocalizedView>
}
