import type {CSSProperties,ReactNode} from 'react';
import {validDocument,type RichNode} from '@/lib/announcement';
export function AnnouncementContent({document}:{document:RichNode}){
 if(!validDocument(document))return <p>Konten announcement tidak valid.</p>;
 function render(n:RichNode,key:number):ReactNode{const children=n.content?.map(render);const a=n.attrs||{};const style:CSSProperties={textAlign:['left','center','right','justify'].includes(String(a.textAlign))?a.textAlign as CSSProperties['textAlign']:undefined};
 if(n.type==='text'){let text:ReactNode=n.text||'';for(const m of n.marks||[]){if(m.type==='bold')text=<strong>{text}</strong>;if(m.type==='italic')text=<em>{text}</em>;if(m.type==='underline')text=<u>{text}</u>;if(m.type==='strike')text=<s>{text}</s>;if(m.type==='textStyle'){const x=m.attrs||{};text=<span style={{fontFamily:['Arial','Georgia','Times New Roman','Courier New'].includes(String(x.fontFamily))?String(x.fontFamily):undefined,fontSize:['12px','14px','16px','18px','24px','32px'].includes(String(x.fontSize))?String(x.fontSize):undefined,color:/^#[0-9a-f]{6}$/i.test(String(x.color))?String(x.color):undefined}}>{text}</span>}}return <span key={key}>{text}</span>}
 switch(n.type){case 'doc':return <div key={key}>{children}</div>;case 'paragraph':return <p key={key} style={style}>{children||<br/>}</p>;case 'heading':return <h3 key={key} style={style}>{children}</h3>;case 'hardBreak':return <br key={key}/>;case 'bulletList':return <ul key={key}>{children}</ul>;case 'orderedList':return <ol key={key}>{children}</ol>;case 'listItem':return <li key={key}>{children}</li>;case 'blockquote':return <blockquote key={key}>{children}</blockquote>;case 'horizontalRule':return <hr key={key}/>;case 'table':return <div className="announcement-table-scroll" key={key}><table><tbody>{children}</tbody></table></div>;case 'tableRow':return <tr key={key}>{children}</tr>;case 'tableCell':case 'tableHeader':{const props={colSpan:Math.max(1,Math.min(20,Number(a.colspan)||1)),rowSpan:Math.max(1,Math.min(20,Number(a.rowspan)||1))};return n.type==='tableHeader'?<th key={key} {...props}>{children}</th>:<td key={key} {...props}>{children}</td>}default:return null}}
 return <div className="announcement-content">{render(document,0)}</div>
}
