'use client';
import {useState} from 'react';
import {Node,mergeAttributes} from '@tiptap/core';
import {validPoll} from '@/lib/announcement-poll';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/animate-ui/components/buttons/button';
import {useFeedbackState} from '@/components/runtime/feedback-toast';
import {LocalizedView} from '@/components/portal/localized-view';

import {useEditor,EditorContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {TextStyleKit} from '@tiptap/extension-text-style';
import {TableKit} from '@tiptap/extension-table';
import TextAlign from '@tiptap/extension-text-align';
import {Bold,Italic,Underline,List,ListOrdered,Table2,Undo,Redo,AlignLeft,AlignCenter,AlignRight,Minus,Trash2,Plus,Vote} from 'lucide-react';
import type {RichNode} from '@/lib/announcement';
const PollNode=Node.create({name:'poll',group:'block',atom:true,draggable:true,addAttributes(){return {id:{default:''},question:{default:''},options:{default:[]},closesAt:{default:''}}},parseHTML(){return [{tag:'div[data-announcement-poll]'}]},renderHTML({node,HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{'data-announcement-poll':'','class':'poll-editor-placeholder'}),`☑ Voting: ${node.attrs.question} — ${node.attrs.options.join(' / ')} · ${new Date(node.attrs.closesAt).toLocaleString('en-GB',{timeZone:'Asia/Jakarta'})} GMT+7`]}});
export default function AnnouncementEditor({value,onChange}:{value:RichNode;onChange:(v:RichNode)=>void}){
 const [open,setOpen]=useState(false),[question,setQuestion]=useState(''),[options,setOptions]=useState(['','']),[deadline,setDeadline]=useState(''),[,setError]=useFeedbackState('');
 function insertPoll(){const config={id:crypto.randomUUID(),question:question.trim(),options:options.map(o=>o.trim()),closesAt:deadline?Number.isFinite(Date.parse(deadline+'+07:00'))?new Date(deadline+'+07:00').toISOString():'':''};if(!config.question){setError('Pertanyaan voting wajib diisi.');return}if(config.options.some(o=>!o)||new Set(config.options.map(o=>o.toLowerCase())).size!==config.options.length){setError('Isi minimal dua pilihan yang berbeda.');return}if(!validPoll(config)||Date.parse(config.closesAt)<=Date.now()){setError('Pilih tanggal dan jam berakhir setelah waktu sekarang (GMT+7).');return}editor?.chain().focus().insertContent({type:'poll',attrs:config}).run();setOpen(false);setQuestion('');setOptions(['','']);setDeadline('')}
 const editor=useEditor({extensions:[PollNode,StarterKit.configure({link:false}),TextStyleKit,TableKit,TextAlign.configure({types:['heading','paragraph']})],immediatelyRender:false,content:value,editorProps:{attributes:{role:'textbox','aria-label':'Announcement content','aria-multiline':'true'}},onUpdate:({editor})=>onChange(editor.getJSON() as RichNode)});
 const actions=[['Bold',Bold,()=>editor?.chain().focus().toggleBold().run()],['Italic',Italic,()=>editor?.chain().focus().toggleItalic().run()],['Underline',Underline,()=>editor?.chain().focus().toggleUnderline().run()],['Bullet list',List,()=>editor?.chain().focus().toggleBulletList().run()],['Numbered list',ListOrdered,()=>editor?.chain().focus().toggleOrderedList().run()],['Align left',AlignLeft,()=>editor?.chain().focus().setTextAlign('left').run()],['Align center',AlignCenter,()=>editor?.chain().focus().setTextAlign('center').run()],['Align right',AlignRight,()=>editor?.chain().focus().setTextAlign('right').run()],['Insert table',Table2,()=>editor?.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run()],['Divider',Minus,()=>editor?.chain().focus().setHorizontalRule().run()],['Undo',Undo,()=>editor?.chain().focus().undo().run()],['Redo',Redo,()=>editor?.chain().focus().redo().run()]] as const;
 return <LocalizedView>{<div className="report-rich-editor announcement-editor"><div className="report-editor-toolbar" role="toolbar" aria-label="Announcement formatting"><select aria-label="Font family" onChange={e=>editor?.chain().focus().setFontFamily(e.target.value).run()}>{['Arial','Georgia','Times New Roman','Courier New'].map(f=><option key={f}>{f}</option>)}</select><select aria-label="Font size" defaultValue="16px" onChange={e=>editor?.chain().focus().setFontSize(e.target.value).run()}>{['12px','14px','16px','18px','24px','32px'].map(f=><option key={f}>{f}</option>)}</select><input type="color" aria-label="Text color" onChange={e=>editor?.chain().focus().setColor(e.target.value).run()}/>{actions.map(([name,Icon,act])=><button key={name} type="button" title={name} aria-label={name} onClick={act}><Icon size={16}/></button>)}<button type="button" title="Insert voting" aria-label="Insert voting" onClick={()=>setOpen(true)}><Vote size={16}/></button>{editor?.isActive('table')&&<><button type="button" aria-label="Add table row" title="Add table row" onClick={()=>editor.chain().focus().addRowAfter().run()}><Plus size={16}/></button><button type="button" aria-label="Add table column" title="Add table column" onClick={()=>editor.chain().focus().addColumnAfter().run()}><Table2 size={16}/></button><button type="button" aria-label="Delete table" title="Delete table" onClick={()=>editor.chain().focus().deleteTable().run()}><Trash2 size={16}/></button></>}</div><EditorContent editor={editor}/><Dialog open={open} onOpenChange={setOpen}><DialogContent className="portal poll-create-dialog"><DialogTitle>Tambahkan Voting</DialogTitle><DialogDescription>Tentukan pilihan dan tanggal berakhir. Satu vote per anggota; pilihan dapat diubah sebelum batas waktu. Voting yang sudah mendapat jawaban tidak dapat diedit atau dihapus.</DialogDescription><label>Pertanyaan<input maxLength={300} value={question} onChange={e=>setQuestion(e.target.value)}/></label>{options.map((option,i)=><label key={i}>Pilihan {i+1}<div className="poll-option-input"><input maxLength={150} value={option} onChange={e=>setOptions(options.map((o,j)=>j===i?e.target.value:o))}/><Button type="button" variant="ghost" size="icon" disabled={options.length<=2} aria-label={`Hapus pilihan ${i+1}`} onClick={()=>setOptions(options.filter((_,j)=>j!==i))}><Trash2 size={15}/></Button></div></label>)}<Button type="button" variant="outline" disabled={options.length>=10} onClick={()=>setOptions([...options,''])}><Plus size={16}/>Tambah Pilihan</Button><label>Berakhir pada (GMT+7)<input type="datetime-local" value={deadline} onInput={e=>setDeadline(e.currentTarget.value)} onChange={e=>setDeadline(e.target.value)}/></label><div className="module-actions"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="button" onClick={insertPoll}>Tambahkan Voting</Button></div></DialogContent></Dialog></div>}</LocalizedView>
}
