'use client';
import {useFeedbackState} from '@/components/runtime/feedback-toast';
import {useState} from 'react';import {useRouter} from 'next/navigation';import {Ellipsis,Pencil,UserMinus} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {DropdownMenu,DropdownMenuContent,DropdownMenuTrigger,DropdownMenuItem} from '@/components/ui/dropdown-menu';import {Switch} from '@/components/ui/switch';import {LocalizedView} from './localized-view';import {usePortal} from './provider';import {accountAccess,canEditMember,canRemoveMember} from '@/lib/member-directory';import type {Profile} from '@/lib/portal-data';import {memberTeams} from '@/lib/member-options';
export function MemberActions({member}:{member:Profile}){
 const {profile,mode,members,logout}=usePortal();const router=useRouter();const [dialog,setDialog]=useState<'edit'|'remove'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useFeedbackState('');
 const [name,setName]=useState(member.name);
 const editAllowed=canEditMember(profile,member),removeAllowed=canRemoveMember(profile,member,members),protectedAccess=accountAccess(member)==='Superadmin';
 function open(value:'edit'|'remove'){setName(member.name);setError('');setDialog(value)}
 async function save(){setError('');if(dialog==='edit'&&!name.trim()){setError('Nama tidak boleh kosong.');document.getElementById(`member-name-${member.id}`)?.focus();return}setBusy(true);try{if(mode==='demo')throw new Error('Pengelolaan member hanya tersedia pada akun live.');const response=await fetch('/api/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:member.id,nameOnly:true,name:name.trim(),remove:dialog==='remove'})});const body=await response.json();if(!response.ok)throw new Error(body.error);setDialog(null);if(dialog==='remove'&&member.id===profile.id){await logout();return}router.refresh()}catch(e){setError(e instanceof Error?e.message:'Perubahan gagal.')}finally{setBusy(false)}}
 return <LocalizedView><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="report-row-action" aria-label={`Action ${member.name}`}><Ellipsis size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="portal report-row-dropdown"><DropdownMenuItem disabled={!editAllowed} onSelect={()=>open('edit')}><Pencil size={15}/>Edit Member</DropdownMenuItem><DropdownMenuItem disabled={!removeAllowed} className="report-delete" onSelect={()=>open('remove')}><UserMinus size={15}/>Remove Member</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!busy)setDialog(null)}}><DialogContent className="portal member-edit-dialog"><DialogTitle>{dialog==='remove'?'Remove Member':'Edit Member'}</DialogTitle><DialogDescription>{dialog==='remove'?'Apakah Anda yakin ingin menghapus akses member ini? Riwayat report tetap tersimpan. Jika ini akun Anda, Anda akan langsung keluar.':'Ubah nama anggota di sini. Penugasan dan akses web dikelola melalui Admin Panel.'}</DialogDescription>{dialog==='edit'?<div className="member-edit-fields"><label className="field">Name<input id={`member-name-${member.id}`} value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><label className="field">Role<input disabled value={member.role||'-'}/></label><label className="field">Division<input disabled value={member.division||'-'}/></label><div className="field"><label>Position</label><div className="member-readonly-positions" role="group" aria-label="Position" aria-disabled="true">{member.position?member.position.split(',').map(v=><span className="badge" key={v}>{v.trim()}</span>):'-'}</div></div><fieldset disabled><legend>Team</legend><div className="settings-teams">{memberTeams.map(team=><label key={team}><input type="checkbox" checked={(member.teams||[]).includes(team)} readOnly disabled/>{team}</label>)}</div></fieldset>{protectedAccess?<p className="member-admin-toggle"><span>Account Access</span><span className="badge">Superadmin</span></p>:<label className="member-admin-toggle"><span>Admin Access</span><Switch disabled checked={accountAccess(member)==='Admin'} aria-label="Admin Access"/></label>}</div>:<p className="member-remove-name" data-no-translate>{member.name}</p>}{error&&<p className="module-error" role="alert">{error}</p>}<div className="report-actions"><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>Cancel</Button><Button variant={dialog==='remove'?'destructive':'default'} disabled={busy} onClick={save}>{busy?'Processing…':dialog==='remove'?'Yes, remove member':'Save Changes'}</Button></div></DialogContent></Dialog></LocalizedView>
}
