'use client';
import {useFeedbackState} from '@/components/runtime/feedback-toast';
import {useState} from 'react';import {useRouter} from 'next/navigation';import {Ellipsis,Pencil,UserMinus} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {DropdownMenu,DropdownMenuContent,DropdownMenuTrigger,DropdownMenuItem} from '@/components/ui/dropdown-menu';import {Switch} from '@/components/ui/switch';import {ReportSelect} from './report-fields';import {LocalizedView} from './localized-view';import {usePortal} from './provider';import {accountAccess} from '@/lib/member-directory';import type {Profile} from '@/lib/portal-data';import {divisions,organizationRoles,positions,memberTeams} from '@/lib/member-options';
export function MemberActions({member}:{member:Profile}){
 const {profile,mode}=usePortal();const router=useRouter();const [dialog,setDialog]=useState<'edit'|'remove'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useFeedbackState('');
 const [name,setName]=useState(member.name),[role,setRole]=useState(organizationRoles.includes(member.role as typeof organizationRoles[number])?member.role:'SAHD'),[division,setDivision]=useState(divisions.includes(member.division as typeof divisions[number])?member.division:''),[position,setPosition]=useState(member.position||'Trainee'),[teams,setTeams]=useState(member.teams||[]),[admin,setAdmin]=useState(accountAccess(member)==='Admin');
 const locked=member.id===profile.id||accountAccess(member)==='Superadmin';
 function open(value:'edit'|'remove'){setName(member.name);setRole(organizationRoles.includes(member.role as typeof organizationRoles[number])?member.role:'SAHD');setDivision(divisions.includes(member.division as typeof divisions[number])?member.division:'');setPosition(member.position||'Trainee');setTeams(member.teams||[]);setAdmin(accountAccess(member)==='Admin');setError('');setDialog(value)}
 async function save(){setError('');if(dialog==='edit'&&!name.trim()){setError('Nama tidak boleh kosong.');document.getElementById(`member-name-${member.id}`)?.focus();return}setBusy(true);try{if(mode==='demo')throw new Error('Pengelolaan member hanya tersedia pada akun live.');const response=await fetch('/api/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:member.id,name:name.trim(),role,division:division||null,position:position||null,teams,access:admin?'Admin':'Member',remove:dialog==='remove'})});const body=await response.json();if(!response.ok)throw new Error(body.error);setDialog(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Perubahan gagal.')}finally{setBusy(false)}}
 const items=(values:readonly string[])=>values.map(value=>({value,label:value}));
 return <LocalizedView><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="report-row-action" aria-label={`Action ${member.name}`}><Ellipsis size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="portal report-row-dropdown"><DropdownMenuItem disabled={locked} onSelect={()=>open('edit')}><Pencil size={15}/>Edit Member</DropdownMenuItem><DropdownMenuItem disabled={locked} className="report-delete" onSelect={()=>open('remove')}><UserMinus size={15}/>Remove Member</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!busy)setDialog(null)}}><DialogContent className="portal member-edit-dialog"><DialogTitle>{dialog==='remove'?'Remove Member':'Edit Member'}</DialogTitle><DialogDescription>{dialog==='remove'?'Apakah Anda yakin ingin menghapus akses member ini? Riwayat report tetap tersimpan.':'Atur identitas, penugasan, dan akses web anggota.'}</DialogDescription>{dialog==='edit'?<div className="member-edit-fields"><label className="field">Name<input id={`member-name-${member.id}`} value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><div className="field"><label>Role</label><ReportSelect label="Role" value={role} items={items(organizationRoles)} onChange={setRole}/></div><div className="field"><label>Division</label><ReportSelect label="Division" value={division||'none'} items={[{value:'none',label:'Unassigned'},...items(divisions)]} onChange={v=>{setDivision(v==='none'?'':v);setPosition('Trainee')}}/></div><div className="field"><label>Position</label><ReportSelect label="Position" value={position||'none'} items={[{value:'none',label:'Unassigned'},...items(positions[division]||['Trainee'])]} onChange={v=>setPosition(v==='none'?'':v)}/></div><fieldset><legend>Team</legend><div className="settings-teams">{memberTeams.map(team=><label key={team}><input type="checkbox" checked={teams.includes(team)} onChange={e=>setTeams(s=>e.target.checked?[...s,team]:s.filter(t=>t!==team))}/>{team}</label>)}</div></fieldset><label className="member-admin-toggle"><span>Admin Access</span><Switch checked={admin} onCheckedChange={setAdmin} aria-label="Admin Access"/></label></div>:<p className="member-remove-name" data-no-translate>{member.name}</p>}{error&&<p className="module-error" role="alert">{error}</p>}<div className="report-actions"><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>Cancel</Button><Button variant={dialog==='remove'?'destructive':'default'} disabled={busy} onClick={save}>{busy?'Processing…':dialog==='remove'?'Yes, remove member':'Save Changes'}</Button></div></DialogContent></Dialog></LocalizedView>
}
