'use client';
import TutorialTour from './tutorial-tour';
import {notificationBell} from '@/lib/notification-sound';
import {canManageMembers} from '@/lib/member-directory';
import {LocalizedView} from '@/components/portal/localized-view';

import {usePreferences} from './preferences';
import { useEffect,useState,useRef } from 'react';import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';import Link from 'next/link';import {usePathname,useRouter} from 'next/navigation';
import { Hash,PanelLeft,LayoutDashboard,FileText,Flame,ClipboardCheck,Sparkles,CalendarDays,Megaphone,Trash2,Search,Bell,ChevronDown,LogOut,Settings,Menu,X,ArrowUpRight,Info,Languages,Sun,Moon } from 'lucide-react';
import { Button } from '@/components/ui/button';import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import { navigation,reportGroups } from '@/lib/portal-data';import {usePortal,Avatar} from './provider';import type {Notice} from '@/lib/portal-data';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuSub,SidebarMenuSubItem,SidebarMenuSubButton,useSidebar} from '@/components/animate-ui/components/radix/sidebar';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
const icons:Record<string,typeof Search>={dashboard:LayoutDashboard,report:FileText,fire:Flame,consent:ClipboardCheck,assistant:Sparkles,calendar:CalendarDays,announcement:Megaphone,trash:Trash2};
export default function Shell({children}:{children:React.ReactNode}){const {profile}=usePortal();useEffect(()=>{document.documentElement.dataset.sahdDivision=profile.division==='Fire Department'?'fd':'ms';return()=>{delete document.documentElement.dataset.sahdDivision}},[profile.division]);return <LocalizedView>{<SidebarProvider className="portal portal-shell"><ShellContent>{children}</ShellContent></SidebarProvider>}</LocalizedView>}
function ShellContent({children}:{children:React.ReactNode}){
 const {t,language,theme,toggleLanguage,toggleTheme}=usePreferences();
 const router=useRouter();const {toggleSidebar,setOpen,setOpenMobile,openMobile,isMobile,state}=useSidebar();
 const reducedMotion=useReducedMotion();const pointerDismiss=useRef(false);
 const {profile,notices,ready,markRead,logout,mode,appointments,error}=usePortal();const path=usePathname();const sidebarRef=useRef<HTMLElement>(null);const menuRef=useRef<HTMLButtonElement>(null);const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[mobile,setMobile]=useState(false),[filter,setFilter]=useState('all'),[feed,setFeed]=useState(false);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v)}if(e.key==='Escape')setMobile(false)};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 useEffect(()=>{setOpenMobile(false);setFeed(false);setSearch(false)},[path,setOpenMobile]);
 const reportPages=reportGroups.flatMap(g=>g.children.map(n=>({...n,group:'Pages'})));
 const results=[...reportPages,...navigation.filter(n=>!n.href.startsWith('/reports')).map(n=>({...n,group:'Pages'})),{label:'Account Settings',href:'/settings/account',group:'Account'},...appointments.map(a=>({label:`${a.name} · ${a.complaint}`,href:`/consultations/${a.id}`,group:'Consultation'}))].filter(r=>[r.label,t(r.label)].some(label=>label.toLowerCase().includes(query.toLowerCase())));
 const availableNavigation=navigation;
 const accountBadges=[...new Set([profile.division,profile.position].flatMap(value=>Array.isArray(value)?value:[value]).map(value=>String(value||'').trim()).filter(value=>value&&value!=='Belum ditetapkan'))];
 const accountName=profile.accountName||profile.name;
 const unreadCount=notices.filter(n=>!n.read).length;
 const filteredNotices=notices.filter(n=>filter==='all'||filter==='mentioned'&&n.type==='mention'||filter==='appointment'&&(n.type==='appointment'||n.type==='mention'&&n.href.startsWith('/consultations/')));
 const [expandedReports,setExpandedReports]=useState<Record<string,boolean>>({});
 const [popups,setPopups]=useState<Notice[]>([]);
 useEffect(()=>{
  const bell=notificationBell();const unlock=()=>bell.unlock();window.addEventListener('pointerdown',unlock);window.addEventListener('keydown',unlock);
  const incoming=(event:Event)=>{const notice=(event as CustomEvent<Notice>).detail;if(profile.notifications&&notice){bell.play();setPopups(previous=>[notice,...previous.filter(n=>n.id!==notice.id)].slice(0,3))}};
  window.addEventListener('sahd-notification-arrived',incoming);
  if(!profile.notifications)setPopups([]);
  return()=>{window.removeEventListener('sahd-notification-arrived',incoming);window.removeEventListener('pointerdown',unlock);window.removeEventListener('keydown',unlock);bell.close()};
 },[profile.notifications]);
 useEffect(()=>{if(!popups.length)return;const timer=setTimeout(()=>setPopups([]),8000);return()=>clearTimeout(timer)},[popups]);
 const current=reportPages.find(n=>path===n.href)?.label||navigation.find(n=>path.startsWith(n.href))?.label||(path.startsWith('/settings')?'Account Settings':'Workspace');
 if(!ready)return <LocalizedView>{<div className="portal"><div className="empty" role="status">Menyiapkan workspace…</div></div>}</LocalizedView>;
 return <LocalizedView>{<><TutorialTour/>
 <Sidebar animateOnHover={false} collapsible="icon" className="sahd-sidebar"><SidebarHeader><Link href="/dashboard" data-tour-brand="true" className="brand portal-brand" aria-label="SAHD Medical Portal"><span className="sidebar-logo-crop"><img src="/sahd-logo.webp" alt="SAHD"/></span><small className="sidebar-label brand-subtitle">Medical Portal</small></Link></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarMenu>{availableNavigation.filter(n=>!n.href.startsWith('/reports')).map(n=>{const Icon=icons[n.icon];return <SidebarMenuItem key={n.href}><SidebarMenuButton asChild isActive={path.startsWith(n.href)} tooltip={t(n.label)}><Link href={n.href} data-tour-nav={n.href} aria-label={n.label} aria-current={path.startsWith(n.href)?'page':undefined}><Icon size={18}/><span>{t(n.label)}</span></Link></SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroup>
 <SidebarGroup><SidebarGroupLabel>{t('Reports')}</SidebarGroupLabel><SidebarMenu>{reportGroups.map(group=>{
  const Icon=icons[group.icon];const open=expandedReports[group.href]??path.startsWith(group.href);const active=path.startsWith(group.href);
  return <SidebarMenuItem key={group.href}>
   <>
    <SidebarMenuButton isActive={active} tooltip={t(group.label)} aria-label={group.label} aria-expanded={(!isMobile&&state==='collapsed'||isMobile&&!openMobile)?false:open} aria-controls={`report-menu-${group.icon}`} onClick={()=>{if((!isMobile&&state==='collapsed')||(isMobile&&!openMobile)){setExpandedReports(previous=>({...previous,[group.href]:true}));setOpen(true);if(isMobile)setOpenMobile(true)}else setExpandedReports(previous=>({...previous,[group.href]:!open}))}}><Icon/><span>{t(group.label)}</span><ChevronDown className={`report-group-chevron ${open?'expanded':''}`} size={16}/></SidebarMenuButton>
    <AnimatePresence initial={false}>{open&&<motion.div id={`report-menu-${group.icon}`} initial={reducedMotion?false:{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.2}} className="report-submenu-wrap"><SidebarMenuSub>{group.children.map(child=><SidebarMenuSubItem key={child.href}><SidebarMenuSubButton asChild isActive={path===child.href}><Link href={child.href} aria-current={path===child.href?'page':undefined}><span>{t(child.label)}</span></Link></SidebarMenuSubButton></SidebarMenuSubItem>)}</SidebarMenuSub></motion.div>}</AnimatePresence>
   </>
  </SidebarMenuItem>
 })}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="flex items-center gap-3 p-2"><Avatar profile={profile}/><div className="sidebar-label"><b className="text-xs"><span data-no-translate>{profile.name}</span></b><p className="muted text-[10px]">{profile.role}</p></div></div>{canManageMembers(profile)&&<SidebarMenuButton asChild tooltip="Admin Panel"><Link href="/admin"><Settings size={17}/><span>Admin Panel</span></Link></SidebarMenuButton>}</SidebarFooter></Sidebar>
 <div className="portal-body">
 <header className="topbar"><button aria-label="Buka atau tutup sidebar" aria-expanded={isMobile?openMobile:state==='expanded'} className="iconbutton" onClick={toggleSidebar}><PanelLeft size={19}/></button><span className="text-xs muted hidden lg:block">Workspace <span className="mx-3 text-slate-300">/</span> <b className="text-slate-600">{t(current)}</b></span><button aria-label="Cari workspace" className="searchtrigger" onClick={()=>{setQuery('');setSearch(true)}}><Search size={15}/><span>{t('Search anything…')}</span><kbd className="ml-auto">⌘K / Ctrl K</kbd></button><div className="ml-auto flex items-center gap-3">{mode==='demo'&&<span className="demo-note"><Info size={13}/>Demo · data contoh</span>}
 <button type="button" className="iconbutton preference-toggle" aria-label={language==='en'?'Switch to Indonesian':'Ganti ke Bahasa Inggris'} title={language==='en'?'Bahasa Indonesia':'English'} onClick={toggleLanguage}><Languages size={18}/><small>{language==='en'?'ENG':'IDN'}</small></button>
 <button type="button" className="iconbutton" aria-label={theme==='light'?'Enable Dark Mode':'Enable Light Mode'} title={theme==='light'?'Dark Mode':'Light Mode'} onClick={toggleTheme}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button>
 <DropdownMenu modal={false} open={feed} onOpenChange={setFeed}><DropdownMenuTrigger asChild><button aria-label="Notifikasi" className="iconbutton"><Bell size={19}/>{notices.some(n=>!n.read)&&<span className="unread"/>}</button></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={12} className="portal nav-dropdown notification-dropdown"><div className="notification-header"><div className="notification-heading"><h2>{t('Notification')}</h2><button disabled={unreadCount===0} onClick={()=>markRead()}>{t('Mark all as read')}</button></div><p className="muted">{unreadCount>0?`You have ${unreadCount} new notifications`:'You’re all caught up'}</p></div><div className="notification-filters" role="group" aria-label="Filter notifikasi">{[['all','All'],['mentioned','Mentioned'],['appointment','Janji Temu']].map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)} className={filter===v?'selected':''}>{t(l)}</button>)}</div><div className="notification-list">{filteredNotices.length===0?<div className="notification-empty" role="status"><span className="notification-icon"><Bell size={22}/></span><b>{t('No Notifications')}</b><p>{filter==='mentioned'?'Mention untuk Anda akan muncul di sini.':filter==='appointment'?'Notifikasi janji temu akan muncul di sini.':'Pengumuman, mention, dan janji temu terbaru akan muncul di sini.'}</p></div>:filteredNotices.map(n=><DropdownMenuItem key={n.id} asChild><Link href={n.href} onClick={()=>markRead(n.id)} className="notification-item"><span className="notification-icon"><Bell size={20}/></span><span className="notification-copy"><b>{n.title}</b><p>{n.body}</p><small>{n.at}</small></span>{!n.read&&<span className="notification-unread" aria-label="Belum dibaca"/>}</Link></DropdownMenuItem>)}</div></DropdownMenuContent></DropdownMenu>
 <DropdownMenu modal={false}><DropdownMenuTrigger asChild><button className="account-trigger" aria-label="User account"><Avatar profile={profile}/><span className="account-copy"><b><span data-no-translate>{accountName}</span></b>{accountBadges.length>0&&<span className="account-badges">{accountBadges.map(badge=><span className="badge" data-division={badge===profile.division?profile.division:undefined} key={badge}>{badge}</span>)}</span>}</span><ChevronDown className="account-chevron" size={16}/></button></DropdownMenuTrigger><DropdownMenuContent sideOffset={12} onPointerDownOutside={()=>{pointerDismiss.current=true}} onEscapeKeyDown={()=>{pointerDismiss.current=false}} onCloseAutoFocus={event=>{if(pointerDismiss.current){event.preventDefault();pointerDismiss.current=false}}} className="portal nav-dropdown account-dropdown" align="end"><div className="account-summary"><Avatar profile={profile}/><div><b><span data-no-translate>{accountName}</span></b>{accountBadges.length>0&&<div className="account-badges">{accountBadges.map(badge=><span className="badge" data-division={badge===profile.division?profile.division:undefined} key={badge}>{badge}</span>)}</div>}</div></div><div className="account-menu-items"><DropdownMenuItem asChild><Link href="/settings/account"><Settings size={17}/>{t('Account Settings')}<ArrowUpRight size={14} className="ml-auto"/></Link></DropdownMenuItem><DropdownMenuItem onClick={logout} className="logout-item"><LogOut size={17}/>{t('Logout')}</DropdownMenuItem></div></DropdownMenuContent></DropdownMenu></div></header>
 <div className="notification-popups" aria-live="polite" aria-relevant="additions"><AnimatePresence>{popups.map(notice=><motion.div key={notice.id} className="notification-popup" initial={reducedMotion?false:{opacity:0,x:24,y:-8}} animate={{opacity:1,x:0,y:0}} exit={{opacity:0,x:24}}><span className="notification-popup-icon"><Bell size={19}/></span><Link href={notice.href} onClick={()=>{markRead(notice.id);setPopups(items=>items.filter(n=>n.id!==notice.id))}}><b>{notice.title}</b><p>{notice.body}</p><small>Lihat detail →</small></Link><button aria-label={`Tutup notifikasi ${notice.title}`} onClick={()=>setPopups(items=>items.filter(n=>n.id!==notice.id))}><X size={16}/></button></motion.div>)}</AnimatePresence></div>
 <motion.main key={path} initial={reducedMotion?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.38,ease:[.22,1,.36,1]}} className="workspace">{mode==='live'&&profile.division==='Belum ditetapkan'&&<div className="announcement"><Info size={17}/><p className="text-xs">Akun Anda belum memiliki divisi. Hubungi admin untuk assignment sebelum mengakses data operasional.</p></div>}{error&&<p role="alert" className="p-3 rounded-lg bg-amber-50 text-amber-800 mb-5 text-xs">{error}</p>}{children}</motion.main>
 <Dialog open={search} onOpenChange={setSearch}><DialogContent showCloseButton={false} className="portal workspace-command"><DialogTitle className="sr-only">Search workspace</DialogTitle><DialogDescription className="sr-only">Cari halaman, pengaturan akun, atau janji temu. Gunakan tombol panah dan Enter untuk memilih.</DialogDescription><Command shouldFilter={false}><div className="command-search-row"><CommandInput aria-label="Cari workspace" value={query} onValueChange={setQuery} placeholder="Cari halaman, pasien, atau kasus…"/><button className="command-escape" onClick={()=>setSearch(false)} aria-label="Tutup pencarian">ESC</button></div><CommandList><CommandEmpty>Tidak ada hasil untuk “{query}”.</CommandEmpty>{['Pages','Account','Consultation'].filter(group=>results.some(r=>r.group===group)).map(group=><CommandGroup key={group} heading={group==='Pages'?'Workspace':group==='Account'?'Account':'Janji temu'}>{results.filter(r=>r.group===group).map(r=><CommandItem key={r.href} value={r.href} onSelect={()=>{setSearch(false);router.push(r.href)}}><span className={group==='Consultation'?'command-child-icon':'command-result-icon'}>{group==='Consultation'?<Hash size={19}/>:<FileText size={19}/>}</span><span>{t(r.label)}</span><ArrowUpRight size={14} className="ml-auto"/></CommandItem>)}</CommandGroup>)}</CommandList><div className="command-footer"><span>↑ ↓ Pilih</span><span>↵ Buka</span><span>Esc Tutup</span></div></Command></DialogContent></Dialog>
 </div></>}</LocalizedView>
}
