'use client';
import { useEffect,useState,useRef } from 'react';import {motion,useReducedMotion} from 'framer-motion';import Link from 'next/link';import {usePathname,useRouter} from 'next/navigation';
import { Hash,PanelLeft,LayoutDashboard,FileText,Flame,ClipboardCheck,Sparkles,CalendarDays,Megaphone,Trash2,Search,Bell,ChevronDown,LogOut,Settings,Menu,X,ArrowUpRight,Info } from 'lucide-react';
import { Button } from '@/components/ui/button';import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import { navigation,demoAppointments } from '@/lib/portal-data';import {usePortal,Avatar} from './provider';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,useSidebar} from '@/components/animate-ui/components/radix/sidebar';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
const icons:Record<string,typeof Search>={dashboard:LayoutDashboard,report:FileText,fire:Flame,consent:ClipboardCheck,assistant:Sparkles,calendar:CalendarDays,announcement:Megaphone,trash:Trash2};
export default function Shell({children}:{children:React.ReactNode}){return <SidebarProvider className="portal portal-shell"><ShellContent>{children}</ShellContent></SidebarProvider>}
function ShellContent({children}:{children:React.ReactNode}){
 const router=useRouter();const {toggleSidebar,setOpenMobile,state}=useSidebar();
 const reducedMotion=useReducedMotion();const pointerDismiss=useRef(false);
 const {profile,notices,ready,markRead,logout,mode,appointments,error}=usePortal();const path=usePathname();const sidebarRef=useRef<HTMLElement>(null);const menuRef=useRef<HTMLButtonElement>(null);const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[mobile,setMobile]=useState(false),[filter,setFilter]=useState('all'),[feed,setFeed]=useState(false);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v)}if(e.key==='Escape')setMobile(false)};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 useEffect(()=>{setOpenMobile(false);setFeed(false);setSearch(false)},[path,setOpenMobile]);
 const results=[...navigation.filter(n=>mode==='demo'||!n.href.startsWith('/reports')||n.href==='/reports/medical'&&profile.division==='Medical Service'||n.href==='/reports/fire'&&profile.division==='Fire Department').map(n=>({...n,group:'Pages'})),{label:'Account settings',href:'/settings/account',group:'Account'},...appointments.map(a=>({label:`${a.name} · ${a.complaint}`,href:`/consultations/${a.id}`,group:'Consultation'}))].filter(r=>r.label.toLowerCase().includes(query.toLowerCase()));
 const availableNavigation=navigation.filter(n=>mode==='demo'||!n.href.startsWith('/reports')||n.href==='/reports/medical'&&profile.division==='Medical Service'||n.href==='/reports/fire'&&profile.division==='Fire Department');
 const accountBadges=[...new Set([profile.role,profile.division].flatMap(value=>Array.isArray(value)?value:[value]).map(value=>String(value||'').trim()).filter(value=>value&&value!=='Belum ditetapkan'))];
 const accountName=profile.accountName||profile.name;
 const unreadCount=notices.filter(n=>!n.read).length;
 const filteredNotices=notices.filter(n=>filter==='all'||filter==='mentioned'&&n.type==='mention'||filter==='appointment'&&(n.type==='appointment'||n.type==='mention'&&n.href.startsWith('/consultations/')));
 const current=navigation.find(n=>path.startsWith(n.href))?.label||(path.startsWith('/settings')?'Account settings':'Workspace');
 if(!ready)return <div className="portal"><div className="empty" role="status">Menyiapkan workspace…</div></div>;
 return <>
 <Sidebar collapsible="icon" className="sahd-sidebar"><SidebarHeader><Link href="/dashboard" className="brand portal-brand" aria-label="SAHD Medical Portal"><img src="/sahd-logo.webp" alt="SAHD"/><small className="sidebar-label brand-subtitle">Medical Portal</small></Link></SidebarHeader><SidebarContent>{[['Workspace',availableNavigation.filter(n=>!n.href.startsWith('/reports'))],['Reports',availableNavigation.filter(n=>n.href.startsWith('/reports'))]].map(([label,items])=><SidebarGroup key={String(label)}><SidebarGroupLabel>{String(label)}</SidebarGroupLabel><SidebarMenu>{(items as typeof navigation).map(n=>{const Icon=icons[n.icon];return <SidebarMenuItem key={n.href}><SidebarMenuButton asChild isActive={path.startsWith(n.href)} tooltip={n.label}><Link href={n.href} aria-current={path.startsWith(n.href)?'page':undefined}><Icon size={18}/><span>{n.label}</span></Link></SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroup>)}</SidebarContent><SidebarFooter><div className="flex items-center gap-3 p-2"><Avatar profile={profile}/><div className="sidebar-label"><b className="text-xs">{profile.name}</b><p className="muted text-[10px]">{profile.role}</p></div></div>{profile.role==='Admin'&&<SidebarMenuButton asChild tooltip="Admin panel"><Link href="/admin"><Settings size={17}/><span>Admin panel</span></Link></SidebarMenuButton>}</SidebarFooter></Sidebar>
 <div className="portal-body">
 <header className="topbar"><button aria-label="Buka atau tutup sidebar" aria-expanded={state==='expanded'} className="iconbutton" onClick={toggleSidebar}><PanelLeft size={19}/></button><span className="text-xs muted hidden lg:block">Workspace <span className="mx-3 text-slate-300">/</span> <b className="text-slate-600">{current}</b></span><button className="searchtrigger" onClick={()=>{setQuery('');setSearch(true)}}><Search size={15}/><span>Search anything…</span><kbd className="ml-auto">⌘K / Ctrl K</kbd></button><div className="ml-auto flex items-center gap-3">{mode==='demo'&&<span className="demo-note"><Info size={13}/>Demo · data contoh</span>}
 <DropdownMenu modal={false} open={feed} onOpenChange={setFeed}><DropdownMenuTrigger asChild><button aria-label="Notifikasi" className="iconbutton"><Bell size={19}/>{notices.some(n=>!n.read)&&<span className="unread"/>}</button></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={12} className="portal nav-dropdown notification-dropdown"><div className="notification-header"><div className="notification-heading"><h2>Notification</h2><button disabled={unreadCount===0} onClick={()=>markRead()}>Mark all as read</button></div><p className="muted">{unreadCount>0?`You have ${unreadCount} new notifications`:'You’re all caught up'}</p></div><div className="notification-filters" role="group" aria-label="Filter notifikasi">{[['all','All'],['mentioned','Mentioned'],['appointment','Janji Temu']].map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)} className={filter===v?'selected':''}>{l}</button>)}</div><div className="notification-list">{filteredNotices.length===0?<div className="notification-empty" role="status"><span className="notification-icon"><Bell size={22}/></span><b>Belum ada notifikasi</b><p>{filter==='mentioned'?'Mention untuk Anda akan muncul di sini.':filter==='appointment'?'Notifikasi janji temu akan muncul di sini.':'Pengumuman, mention, dan janji temu terbaru akan muncul di sini.'}</p></div>:filteredNotices.map(n=><DropdownMenuItem key={n.id} asChild><Link href={n.href} onClick={()=>markRead(n.id)} className="notification-item"><span className="notification-icon"><Bell size={20}/></span><span className="notification-copy"><b>{n.title}</b><p>{n.body}</p><small>{n.at}</small></span>{!n.read&&<span className="notification-unread" aria-label="Belum dibaca"/>}</Link></DropdownMenuItem>)}</div></DropdownMenuContent></DropdownMenu>
 <DropdownMenu modal={false}><DropdownMenuTrigger asChild><button className="account-trigger" aria-label="User account"><Avatar profile={profile}/><span className="account-copy"><b>{accountName}</b>{accountBadges.length>0&&<span className="account-badges">{accountBadges.map(badge=><span className="badge" key={badge}>{badge}</span>)}</span>}</span><ChevronDown className="account-chevron" size={16}/></button></DropdownMenuTrigger><DropdownMenuContent sideOffset={12} onPointerDownOutside={()=>{pointerDismiss.current=true}} onEscapeKeyDown={()=>{pointerDismiss.current=false}} onCloseAutoFocus={event=>{if(pointerDismiss.current){event.preventDefault();pointerDismiss.current=false}}} className="portal nav-dropdown account-dropdown" align="end"><div className="account-summary"><Avatar profile={profile}/><div><b>{accountName}</b>{accountBadges.length>0&&<div className="account-badges">{accountBadges.map(badge=><span className="badge" key={badge}>{badge}</span>)}</div>}</div></div><div className="account-menu-items"><DropdownMenuItem asChild><Link href="/settings/account"><Settings size={17}/>Account settings<ArrowUpRight size={14} className="ml-auto"/></Link></DropdownMenuItem><DropdownMenuItem onClick={logout} className="logout-item"><LogOut size={17}/>Logout</DropdownMenuItem></div></DropdownMenuContent></DropdownMenu></div></header>
 <motion.main key={path} initial={reducedMotion?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.38,ease:[.22,1,.36,1]}} className="workspace">{mode==='live'&&profile.division==='Belum ditetapkan'&&<div className="announcement"><Info size={17}/><p className="text-xs">Akun Anda belum memiliki divisi. Hubungi admin untuk assignment sebelum mengakses data operasional.</p></div>}{error&&<p role="alert" className="p-3 rounded-lg bg-amber-50 text-amber-800 mb-5 text-xs">{error}</p>}{children}</motion.main>
 <Dialog open={search} onOpenChange={setSearch}><DialogContent showCloseButton={false} className="portal workspace-command"><DialogTitle className="sr-only">Search workspace</DialogTitle><DialogDescription className="sr-only">Cari halaman, pengaturan akun, atau janji temu. Gunakan tombol panah dan Enter untuk memilih.</DialogDescription><Command shouldFilter={false}><div className="command-search-row"><CommandInput aria-label="Cari workspace" value={query} onValueChange={setQuery} placeholder="Cari halaman, pasien, atau kasus…"/><button className="command-escape" onClick={()=>setSearch(false)} aria-label="Tutup pencarian">ESC</button></div><CommandList><CommandEmpty>Tidak ada hasil untuk “{query}”.</CommandEmpty>{['Pages','Account','Consultation'].filter(group=>results.some(r=>r.group===group)).map(group=><CommandGroup key={group} heading={group==='Pages'?'Workspace':group==='Account'?'Account':'Janji temu'}>{results.filter(r=>r.group===group).map(r=><CommandItem key={r.href} value={r.href} onSelect={()=>{setSearch(false);router.push(r.href)}}><span className={group==='Consultation'?'command-child-icon':'command-result-icon'}>{group==='Consultation'?<Hash size={19}/>:<FileText size={19}/>}</span><span>{r.label}</span><ArrowUpRight size={14} className="ml-auto"/></CommandItem>)}</CommandGroup>)}</CommandList><div className="command-footer"><span>↑ ↓ Pilih</span><span>↵ Buka</span><span>Esc Tutup</span></div></Command></DialogContent></Dialog>
 </div></>
}
