'use client';
import {LocalizedView} from './localized-view';
import {createPortal} from 'react-dom';
import {useEffect,useState,useRef} from 'react';import {Compass,ArrowLeft,ArrowRight,Check} from 'lucide-react';
import {Button} from '@/components/animate-ui/components/buttons/button';import {usePortal} from './provider';import {usePreferences} from './preferences';
const steps=[
 {title:['Selamat Datang di SAHD','Welcome to SAHD'],body:['Gunakan nama karakter Anda di server Executive RP agar anggota lain mudah mengenali Anda. Mengubah nama bersifat opsional.','Use your character name from the Executive RP server so teammates can recognize you. Changing your name is optional.'],target:''},
 {title:['Dashboard','Dashboard'],body:['Lihat pengumuman terbaru, ringkasan surgery dan Big Fire, grafik aktivitas, serta jadwal konsultasi.','See the latest announcements, surgery and Big Fire totals, activity charts, and consultation schedules.'],target:'/dashboard'},
 {title:['Patient Consent','Patient Consent'],body:['Buat consent, isi identitas pasien dan emergency contact. Signature terisi dari nama; Anda dapat preview dan export dokumen.','Create a consent and enter patient and emergency contact information. Signatures use their names; preview and export the document.'],target:'/patient-consents'},
 {title:['Case Assistant & Reports','Case Assistant & Reports'],body:['Masukkan kasus RP di Case Assistant. Anggota yang memiliki akses menulis dapat menyalin hasil ke Surgery Report. Akses report mengikuti divisi dan jabatan Anda.','Enter an RP case in Case Assistant. Members with write access can copy the result to a Surgery Report. Report permissions follow your division and position.'],target:'/case-assistant'},
 {title:['Consultation & Mentions','Consultation & Mentions'],body:['Buat janji temu dan tag Divisi, Members, atau Position. Klik baris untuk detail. Anggota yang disebut dapat melakukan approval; Trainee hanya membuat dan menghapus konsultasi miliknya.','Create an appointment and tag Division, Members, or Position. Click a row for details. Mentioned members can approve; Trainees can create and delete their own consultations.'],target:'/consultations'},
 {title:['Announcement & Notifications','Announcement & Notifications'],body:['Baca pengumuman dan attachment. Notifikasi baru muncul dengan popup dan suara bell setelah Anda berinteraksi dengan halaman, jika notifikasi aktif.','Read announcements and attachments. New notifications appear with a popup and bell after you interact with the page, when notifications are enabled.'],target:'/announcements'},
 {title:['Trash & Account Settings','Trash & Account Settings'],body:['Data yang dihapus sementara dapat dipulihkan dari Trash selama 30 hari. Ubah profil di Account Settings dan klik Start Tutorial kapan pun untuk mengulang panduan.','Restore temporarily deleted items from Trash within 30 days. Update your profile in Account Settings and click Start Tutorial anytime to replay this guide.'],target:'/trash'}
];
export default function TutorialTour(){
 const {profile,mode,saveProfile}=usePortal(),{language}=usePreferences(),[open,setOpen]=useState(false),[step,setStep]=useState(0),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[firstStep,setFirstStep]=useState(0),[rects,setRects]=useState<{x:number;y:number;width:number;height:number}[]>([]),[placement,setPlacement]=useState({left:20,top:100});const cardRef=useRef<HTMLDivElement>(null);const profileRef=useRef(profile);profileRef.current=profile;const key=`sahd-tutorial:${profile.id}`,l=language==='id'?0:1;
 useEffect(()=>{const start=(replay=false)=>{setFirstStep(replay?1:0);setStep(replay?1:0);setName(profileRef.current.name);setError('');setOpen(true)};const replay=()=>start(true);window.addEventListener('sahd-start-tutorial',replay);if((mode==='demo'||profile.tutorialCompleted===false)&&!localStorage.getItem(key))start();return()=>window.removeEventListener('sahd-start-tutorial',replay)},[profile.id,profile.tutorialCompleted,mode,key]);
 useEffect(()=>{
  if(!open)return;
  const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;
  const frame=requestAnimationFrame(()=>cardRef.current?.focus());
  return()=>{cancelAnimationFrame(frame);previous?.focus({preventScroll:true})};
 },[open]);
 useEffect(()=>{
  if(!open)return;
  const target=document.querySelector<HTMLElement>(`[data-tour-nav="${steps[step].target}"]`);
  target?.scrollIntoView({block:'nearest',behavior:'instant'});
  const measure=()=>{
   const targets=[target,...(step===1?[document.querySelector<HTMLElement>('[data-tour-brand]')]:[])].filter((el):el is HTMLElement=>!!el);
   const boxes=targets.map(el=>el.getBoundingClientRect()).filter(r=>r.width>0&&r.height>0).map(r=>({x:r.left-7,y:r.top-7,width:r.width+14,height:r.height+14}));setRects(boxes);
   const width=Math.min(400,window.innerWidth-32),height=cardRef.current?.offsetHeight||350,anchor=boxes[0];
   const left=anchor&&anchor.x+anchor.width+width+32<window.innerWidth?anchor.x+anchor.width+20:Math.max(16,(window.innerWidth-width)/2);
   const top=anchor?Math.max(16,Math.min(anchor.y+anchor.height+18,window.innerHeight-height-16)):Math.max(16,(window.innerHeight-height)/2);
   setPlacement({left,top});
  };
  measure();const observer=new ResizeObserver(measure);if(cardRef.current)observer.observe(cardRef.current);if(target)observer.observe(target);
  window.addEventListener('resize',measure);window.addEventListener('scroll',measure,true);
  return()=>{observer.disconnect();window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure,true)};
 },[open,step,language]);
 async function finish(){setBusy(true);setError('');try{if(mode==='live'){const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete_tutorial'})});if(!r.ok)throw Error((await r.json()).error)}localStorage.setItem(key,'completed');setOpen(false)}catch(e){setError(e instanceof Error?e.message:'Tutorial gagal disimpan.')}finally{setBusy(false)}}
 async function next(){setBusy(true);setError('');try{if(step===0){if(name.trim()&&name.trim()!==profile.name)await saveProfile({...profile,name:name.trim()});if(mode==='live'){const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete_tutorial'})});if(!r.ok)throw Error('Unable to save your welcome preferences.');}localStorage.setItem(key,'completed');setFirstStep(1);}setStep(s=>Math.min(s+1,steps.length-1))}catch(e){setError(e instanceof Error?e.message:'Nama gagal disimpan.')}finally{setBusy(false)}}
 if(!open)return null;
 return createPortal(<LocalizedView><div className="tutorial-layer" onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();void finish()}if(e.key==='Tab'){const nodes=cardRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===cardRef.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><svg className="tutorial-spotlights" width="100%" height="100%" aria-hidden="true"><defs><mask id="sahd-tour-mask"><rect width="100%" height="100%" fill="white"/>{rects.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.width} height={r.height} rx="20" fill="black"/>)}</mask></defs><rect width="100%" height="100%" fill="rgba(5,15,25,.66)" mask="url(#sahd-tour-mask)"/>{rects.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.width} height={r.height} rx="20" fill="none" stroke="#5ee4bd" strokeWidth="3"/>)}</svg><div ref={cardRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="tutorial-title" aria-describedby="tutorial-description" className="portal tutorial-tour tutorial-tooltip" style={placement}><span className="tutorial-step"><Compass size={18}/>{l===0?'Panduan Portal':'Portal Guide'} · {step-firstStep+1}/{steps.length-firstStep}</span><h2 id="tutorial-title">{steps[step].title[l]}</h2><p id="tutorial-description">{steps[step].body[l]}</p>{step===0&&<label className="tutorial-name">{l===0?'Nama Karakter (opsional)':'Character Name (optional)'}<input aria-label="Character name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><small className="muted">{l===0?'Biarkan nama saat ini jika belum ingin menggantinya.':'Keep your current name if you prefer to change it later.'}</small></label>}<div className="tutorial-progress" aria-hidden="true">{steps.map((_,i)=>i>=firstStep&&<span key={i} data-current={i<=step}/>)}</div>{error&&<p role="alert" className="module-error">{error}</p>}<div className="tutorial-actions"><Button variant="link" disabled={busy} onClick={finish}>Skip</Button><div><Button variant="outline" disabled={busy||step===firstStep} onClick={()=>{setStep(s=>s-1);setError('')}}><ArrowLeft size={15}/>Previous</Button>{step===steps.length-1?<Button disabled={busy} onClick={finish}><Check size={15}/>{busy?'Saving…':'Finish'}</Button>:<Button disabled={busy} onClick={next}>{busy?'Saving…':'Next'}<ArrowRight size={15}/></Button>}</div></div></div></div></LocalizedView>,document.body)
}
