import Link from 'next/link';
import MedicalOrganization from './medical-organization';
import FireOrganization from './fire-organization';
import { ArrowUpRight, ArrowLeft, HeartPulse, Flame, ShieldCheck } from 'lucide-react';
import { SiteHeader, SiteFooter } from './site-chrome';
import { facilities, specialists } from './medical-data';
const medicalServices = [ ['Treatment','Health assessments, wound care, first aid, and routine medical support.'], ['Inpatient Care','Observation, ongoing treatment, and supported recovery in a comfortable environment.'], ['Plastic Surgery','Consultation and reconstructive or cosmetic procedures for your character.'], ['Major & Minor Surgery','From minor procedures to complex operations, with appropriate anesthesia, coordinated care, and postoperative monitoring.'] ];
const fireServices = [ ['Fire Suppression','Responding to building, vehicle, and outdoor fires to protect the community.'], ['Technical Rescue','Assisting people trapped in vehicles or difficult-to-access areas.'], ['Emergency Evacuation','Helping residents leave hazardous scenes and reach safer locations.'], ['Medical Coordination','Working with Medical Service to transfer casualties into appropriate care.'] ];
export default function DivisionPage({fire=false}:{fire?:boolean}){
const name=fire?'Fire Department':'Medical Service'; const Icon=fire?Flame:HeartPulse;
const outfitPhotos: Record<string,string> = {'Clinical Uniform':'/outfits/clinical.jpeg','Field Uniform':'/outfits/field.png','Surgical Attire':'/outfits/surgical.jpeg','Station Uniform':'/outfits/station.webp','Turnout Gear':'/outfits/turnout.png','Rescue Uniform':'/outfits/rescue.png'};
const outfits=fire?[['Station Uniform','Daily station duties','A practical duty shirt, service trousers, boots, and visible department identification.'],['Turnout Gear','Fire response','Fire helmets, department shirts, reflective duty trousers, gloves, and boots for fire response.'],['Rescue Uniform','Technical rescue','Yellow rescue suits with reflective bands, gloves, boots, and equipment for technical rescue.']]:[['Clinical Uniform','Hospital care','Scrubs, closed footwear, and visible staff identification for clinical duties.'],['Field Uniform','Emergency response','A white medical coat over a duty shirt and tie, paired with a stethoscope for field duties.'],['Surgical Attire','Operating room','Surgical scrubs, cap, mask, and procedure-appropriate protective equipment.']];
return <div className={fire?"division-shell fire-theme":"division-shell"}><SiteHeader/><main className="division-page"><section className="division-page-hero photographic-hero"><img className="division-hero-photo" src={fire?"/fire-hero.webp":"/medical-hero.webp"} alt={fire?"Fire Department team overlooking Los Santos at night":"Medical Service doctors together on duty"} fetchPriority="high"/><div className="division-hero-shade" aria-hidden="true"/><Link href="/" className="back-link"><ArrowLeft size={15}/> Back to Home</Link><div className="eyebrow">EXECUTIVE RP · {fire?'FIRE & RESCUE':'HEALTH & MEDICINE'}</div><Icon className="division-watermark" size={190} strokeWidth={.8}/><h1>{name}<br/><em>{fire?'Courage in every call.':'Care beyond duty.'}</em></h1><p>{fire?'Protecting our community through fire response, rescue, and coordinated emergency support.':'From first response to recovery, our people bring skill and compassion to every patient story.'}</p><nav className="division-section-nav" aria-label="On this page">{['Organization',...(!fire?['Facilities']:[]),'Services',...(!fire?['Specialties']:[]),'Outfits',...(fire?['Vehicle Units']:[])].map(label=><a key={label} href={'#'+label.toLowerCase().replaceAll(' ','-')}>{label}</a>)}</nav></section>
<section className="section" id="organization"><div className="section-heading"><div><div className="eyebrow">OUR PEOPLE, CONNECTED</div><h2>A clear structure.<br/><em>One shared mission.</em></h2></div><p>Leadership, coordination, and specialist teams<br/>working together across the division.</p></div>{fire?<FireOrganization/>:<MedicalOrganization/>}</section>
{!fire&&<section className="section division-tint" id="facilities"><div className="eyebrow">SPACES THAT SUPPORT RECOVERY</div><h2>Our facilities.</h2><div className="division-content-grid facilities-detail">{facilities.map(f=><article key={f.title}><img loading="lazy" src={f.image} alt={f.imageAlt}/><div><h3>{f.title}</h3><p>{f.text}</p></div></article>)}</div></section>}
<section className={'section '+(fire?'division-tint':'')} id="services"><div className="eyebrow">READY WHEN IT MATTERS</div><h2>{fire?'Response & rescue.':'Our medical services.'}</h2><div className="division-content-grid">{(fire?fireServices:medicalServices).map(([title,text],i)=><article className="division-info-card" key={title}><span className="card-index">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
{!fire&&<section className="section division-tint" id="specialties"><div className="eyebrow">EXPERTISE ACROSS DISCIPLINES</div><h2>Our medical specialties.</h2><div className="specialty-detail-grid">{specialists.map(s=><article className="division-info-card" key={s.name}><s.icon size={25} strokeWidth={1.4}/><h3>{s.name}</h3><span className="specialty-sub">{s.en}</span><p>{s.desc}</p></article>)}</div></section>}
<section className="section" id="outfits"><div className="section-heading"><div><div className="eyebrow">IDENTITY IN EVERY DETAIL</div><h2>Dressed for duty.</h2></div><p>Recognizable, practical, and suited to the role.</p></div><div className={fire?"outfit-grid fire-outfits":"outfit-grid"}>{outfits.map(([title,tag,description])=><article className="outfit-card" key={title}><div className={'outfit-photo '+(title==='Field Uniform'?'field-uniform':'')}><img loading="lazy" src={outfitPhotos[title]} alt={title+' worn by '+name+' personnel'}/></div><div><div className="eyebrow">{tag}</div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
{fire&&<section className="section division-tint" id="vehicle-units">
<div className="section-heading"><div><div className="eyebrow">EQUIPPED TO RESPOND</div><h2>Vehicle units.</h2></div><p>The right capability for each response.</p></div>
<div className="vehicle-grid">
<article className="vehicle-card">
<div className="vehicle-photo command-photo"><img loading="lazy" src="/vehicles/command.webp" alt="SAFR ambulance used as the Command Vehicle"/></div>
<div className="vehicle-copy"><div className="eyebrow">Incident coordination</div><h3>Command Vehicle</h3><p>Supports field supervision and coordination between responding teams.</p></div>
</article>
<article className="vehicle-card">
<div className="vehicle-photo"><img loading="lazy" src="/vehicles/fire-engine.webp" alt="Red Los Santos Fire Department fire engine"/></div>
<div className="vehicle-copy"><div className="eyebrow">Fire suppression</div><h3>Fire Engine</h3><p>Carries a crew and firefighting equipment for fire response.</p></div>
</article>
<article className="vehicle-card rescue-vehicle">
<div className="rescue-photos">
<div className="vehicle-photo"><img loading="lazy" src="/vehicles/rescue-air.webp" alt="San Andreas search and rescue helicopter in flight"/></div>
<div className="vehicle-photo"><img loading="lazy" src="/vehicles/rescue-heavy.webp" alt="Yellow and white fire rescue helicopter on the ground"/></div>
</div>
<div className="vehicle-copy"><div className="eyebrow">Air rescue</div><h3>Rescue Unit</h3><p>Helicopters support search and rescue operations, transporting rescue personnel and reaching difficult-to-access locations.</p></div>
</article>
</div></section>}
<section className="closing"><ShieldCheck size={36}/><div><div className="eyebrow">TWO DIVISIONS. ONE COMMUNITY.</div><h2>Stronger <em>together.</em></h2></div><Link className="button light" href={fire?'/medical-service':'/fire-department'}>Explore {fire?'Medical Service':'Fire Department'}<ArrowUpRight size={17}/></Link></section></main><SiteFooter/></div>
}
