import type { ReactNode } from 'react';
const leadership = ['Hospital Director', 'Deputy Hospital Director', 'Advisor to the Hospital Director'];
const medicalCommand = ['Chief Medical Service', 'Deputy Medical Service'];
const medicalRanks = [ 'Attending Physician', 'Resident Physician', 'General Practitioner', 'Medical Student', 'Trainee'];
const departments = ['Human Resources', 'Finance', 'Public Relations', 'Internal Affairs'];
function Chain({roles,children}:{roles:string[];children?:ReactNode}):ReactNode {
 const [role,...remaining]=roles;
 return <li><div className={'hierarchy-node '+(role==='Hospital Director'?'hierarchy-head':'')}><strong>{role}</strong></div>{remaining.length>0?<ul><Chain roles={remaining}>{children}</Chain></ul>:children}</li>;
}
export default function MedicalOrganization(){return <div className="medical-organization">
 <section aria-labelledby="medical-hierarchy-title" className="hierarchy-panel"><div className="eyebrow">01 / MEDICAL SERVICE</div><h3 id="medical-hierarchy-title">Medical hierarchy</h3><p className="hierarchy-description">From hospital leadership to the next generation of medical professionals.</p><div className="hierarchy-chart clinical-chart"><ul aria-label="Medical Service hierarchy"><Chain roles={[...leadership,...medicalCommand]}><div className="hospital-branch"><svg className="branch-connector" viewBox="0 0 100 44" preserveAspectRatio="none" aria-hidden="true"><path d="M50 0 V22 M25 44 V22 H75 V44"/></svg><ul className="hospital-heads" aria-label="Hospital heads at the same level"><li><div className="hierarchy-node department-node"><strong>Head of LSMC</strong></div></li><li><div className="hierarchy-node department-node"><strong>Head of SSMC</strong></div></li></ul><svg className="branch-connector" viewBox="0 0 100 44" preserveAspectRatio="none" aria-hidden="true"><path d="M25 0 V22 H75 V0 M50 22 V44"/></svg><ul className="merged-command" aria-label="Shared medical ranks"><Chain roles={medicalRanks}/></ul></div></Chain></ul></div></section>
 <section aria-labelledby="management-hierarchy-title" className="hierarchy-panel" id="management"><div className="eyebrow">02 / HOSPITAL MANAGEMENT</div><h3 id="management-hierarchy-title">Management organization</h3><p className="hierarchy-description">Four departments at the same level, each with its own Chief, Deputy, and Person in Charge.</p><div className="hierarchy-scroll" tabIndex={0} role="region" aria-label="Management organization chart; scroll horizontally on smaller screens"><div className="hierarchy-chart management-chart"><ul aria-label="Hospital management hierarchy"><Chain roles={[...leadership,...medicalCommand]}><ul className="management-branches">{departments.map(department=><li key={department}><div className="hierarchy-node department-node"><strong>{department}</strong></div><ul><Chain roles={['Chief','Deputy','PIC (Person in Charge)']}/></ul></li>)}</ul></Chain></ul></div></div><p className="chart-scroll-hint">Scroll horizontally to explore all four departments.</p></section>
 </div>}
