'use client';
import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { SiteHeader, SiteFooter } from './site-chrome';
import { facilities, specialists } from './medical-data';
import LocationMap from './location-map';
import { ArrowUpRight, Cross, HeartPulse, Clock3, MapPin, X, BedDouble, Scissors, Stethoscope, ChevronDown, Flame } from 'lucide-react';
const reveal = {initial:{opacity:0,y:25},whileInView:{opacity:1,y:0},viewport:{once:true,amount:0.15},transition:{duration:0.6}};
export default function Home(){
 const [detail,setDetail]=useState<typeof facilities[number]|null>(null); const [specialty,setSpecialty]=useState<number|null>(0); const [location,setLocation]=useState(0);
 useEffect(()=>{if(!detail)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDetail(null)};document.addEventListener('keydown',close); const old=document.body.style.overflow; document.body.style.overflow='hidden'; return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=old}},[detail]);
 return <>
 <SiteHeader/>
 <main>
 <section className="immersive-hero" id="home"><img className="hero-backdrop" src="/executive-team.png" alt="Executive Roleplay team at Vinewood"/><div className="hero-scrim"/><motion.div className="hero-center" {...reveal}><div className="eyebrow"><span/> EXECUTIVE RP MEDICAL CENTER</div><h1>Dedicated to life.<br/><em>United in care.</em></h1><p>For every call. For every story. For every life.<br/>Your community. Our commitment.</p><div className="hero-actions"><a className="button" href="/medical-service"><HeartPulse size={18}/> Medical Service <ArrowUpRight size={17}/></a><a className="button hero-secondary" href="/fire-department"><Flame size={18}/> Fire Department <ArrowUpRight size={17}/></a></div></motion.div><div className="hero-bottomline"><span><span className="status-dot"/> ALWAYS ON CALL</span><span>LOS SANTOS & SANDY SHORES</span><a href="#divisions">DISCOVER OUR DIVISIONS ↓</a></div></section>
 <section className="stats" aria-label="Our commitment to care"><div><strong>24<span>/</span>7</strong><p>Ready whenever you need us<small>Emergency care</small></p></div><div><strong>05<span>+</span></strong><p>Expertise that works together<small>Medical specialties</small></p></div><div><strong>02</strong><p>Closer to your community<small>Care locations</small></p></div><div className="stats-note"><Cross size={25}/><p>One commitment.<br/><b>Your health.</b></p></div></section>
 <section className="section divisions" id="divisions"><motion.div className="section-heading" {...reveal}><div><div className="eyebrow">TWO DIVISIONS. ONE COMMITMENT.</div><h2>United in service.<br/><em>Dedicated to protection.</em></h2></div><p>Two divisions with distinct expertise,<br/>working together for the safety of<br/>Executive Roleplay.</p></motion.div><div className="division-grid"><article id="medical-service" className="division-card"><div className="division-icon"><HeartPulse size={28} strokeWidth={1.4}/></div><div className="eyebrow">01 / MEDICAL DIVISION</div><h3>Medical Service</h3><p>Caring for our community, from first aid in the field to treatment at the hospital. Our medical team supports patients through every stage of care and recovery.</p><ul><li>Medical response & patient transport</li><li>Treatment, inpatient care & surgery</li><li>Specialist consultations</li></ul><a className="text-link" href="/medical-service">Explore Medical Service <ArrowUpRight size={16}/></a></article><article id="fire-department" className="division-card fire-division"><div className="division-icon"><Flame size={28} strokeWidth={1.4}/></div><div className="eyebrow">02 / FIRE & RESCUE DIVISION</div><h3>Fire Department</h3><p>Protecting our community through fire response and rescue operations. The team coordinates with medical personnel to assist casualties and secure emergency scenes.</p><ul><li>Fire response & suppression</li><li>Rescue & evacuation from hazardous areas</li><li>Coordinated emergency response with medical teams</li></ul><a className="text-link" href="/fire-department">Explore Fire Department <ArrowUpRight size={16}/></a></article></div></section>
 <section className="section facilities" id="facility"><motion.div className="section-heading" {...reveal}><div><div className="eyebrow">DESIGNED FOR BETTER CARE</div><h2>Exceptional facilities.<br/><em>For every need.</em></h2></div><p>An environment that supports healing.<br/>Equipped for a wide range of needs,<br/>designed around your comfort.</p></motion.div><div className="facility-grid">{facilities.map((f,i)=><motion.button {...reveal} transition={{duration:.5,delay:i*.07}} className="facility-card" key={f.title} onClick={()=>setDetail(f)}><div key="photo" className="facility-photo"><img loading="lazy" src={f.image} alt={f.imageAlt}/><span>{f.tag}</span><div className="circle-arrow"><ArrowUpRight size={20}/></div></div><h3 key="title">{f.title}</h3><p key="subtitle">{f.sub}</p></motion.button>)}</div></section>
 <section className="services section" id="services"><motion.div className="service-intro" {...reveal}><div className="eyebrow">WITH YOU, EVERY STEP</div><h2>Comprehensive care.<br/><em>With all our heart.</em></h2><p>From your first consultation to recovery,<br/>we are here to help you receive<br/>the care you need.</p><div className="service-seal"><Cross size={34}/><span>EXPERTISE YOU CAN TRUST<br/><b>Care beyond duty.</b></span></div></motion.div><div className="service-grid">{[{icon:Stethoscope,title:'Treatment',text:'Health assessments, wound treatment, and medical care to support your everyday life.'},{icon:BedDouble,title:'Inpatient Care',text:'Continued care and observation by our medical team in a safe, comfortable environment.'},{icon:Scissors,title:'Plastic Surgery',text:'Reconstructive and cosmetic consultations and procedures tailored to your character.'},{icon:HeartPulse,title:'Major & Minor Surgery',text:'Minor procedures and complex operations, with careful preparation, appropriate anesthesia, and coordinated recovery.'}].map((s,i)=><motion.div {...reveal} key={s.title} className="service-card"><div key="icon" className="service-card-top"><s.icon size={25} strokeWidth={1.3}/><span>0{i+1}</span></div><h3 key="title">{s.title}</h3><p key="description">{s.text}</p></motion.div>)}</div></section>
 <section className="section doctors" id="doctors"><motion.div {...reveal}><div className="eyebrow">THE PEOPLE BEHIND THE CARE</div><h2>The expertise you need.<br/><em>The compassion you deserve.</em></h2><p className="section-desc">Different specialties, one purpose: delivering the best possible care for you.</p></motion.div><div className="doctor-layout"><div className="doctor-image"><img loading="lazy" src="/medical-doctor.png" alt="Doctor in a white coat with a stethoscope"/><div><Cross size={25}/><p>Expert hands.<br/><em>Human hearts.</em></p></div></div><div className="specialists">{specialists.map((s,i)=><div className={'specialist '+(specialty===i?'active':'')} key={s.name}><button aria-expanded={specialty===i} onClick={()=>setSpecialty(specialty===i?null:i)}><s.icon size={23} strokeWidth={1.4}/><span>{s.name}<small>{s.en}</small></span><ChevronDown size={18}/></button><AnimatePresence initial={false}>{specialty===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p>{s.desc}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>
 <section className="locations section" id="locations"><div className="location-info"><div className="eyebrow">CLOSER TO YOU</div><h2>At the heart of the city.<br/><em>Right by your side.</em></h2><p>Find Executive Medical Center care<br/>at two locations across San Andreas.</p><div className="location-options">{['Los Santos','Sandy Shores'].map((l,i)=><button key={l} className={location===i?'selected':''} onClick={()=>setLocation(i)}><MapPin size={20}/><span>{l}<small>{i===0?'San Andreas Avenue · Los Santos':'Alhambra Drive · Sandy Shores'}</small></span><ArrowUpRight size={20}/></button>)}</div><span className="location-footnote"><Clock3 size={14}/> Emergency care available 24/7</span></div><LocationMap location={location}/></section>
 <section className="closing"><span className="closing-cross"><Cross size={46} strokeWidth={1}/></span><div><div className="eyebrow">HERE FOR EVERY STORY</div><h2>Because every life <em>matters.</em></h2><p>Here to care, to support, and to help you move forward.</p></div><a href="#home" className="button light">Back to Top <ArrowUpRight size={17}/></a></section>
 </main><SiteFooter/>
 <AnimatePresence>{detail&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setDetail(null)}><motion.div role="dialog" aria-modal="true" aria-labelledby="modal-title" className="modal" initial={{y:30,scale:.97}} animate={{y:0,scale:1}} onClick={e=>e.stopPropagation()}><button autoFocus className="modal-close" onClick={()=>setDetail(null)} aria-label="Close details"><X/></button><img src={detail.image} alt={detail.imageAlt}/><div className="modal-content"><div className="eyebrow">{detail.tag}</div><h2 id="modal-title">{detail.title}</h2><p>{detail.text}</p><a className="button" href="#locations" onClick={()=>setDetail(null)}>View Locations <ArrowUpRight size={17}/></a></div></motion.div></motion.div>}</AnimatePresence>
 </>
}
