import {validPoll} from './announcement-poll';
import type {AnnouncementAttachment} from './announcement-attachments';
import {bounds,wibDate,type Period} from './analytics';
export type RichNode={type:string;text?:string;attrs?:Record<string,unknown>;marks?:{type:string;attrs?:Record<string,unknown>}[];content?:RichNode[]};
export type AnnouncementRow={id:string;title:string;subtitle:string;body_json:RichNode;body_text:string;created_by:string;created_by_name:string;created_at:string;published_at:string;deleted_at?:string|null;purge_after?:string|null;attachments?:AnnouncementAttachment[];is_pinned?:boolean};
export const emptyDocument:RichNode={type:'doc',content:[{type:'paragraph'}]};
const nodes=new Set(['doc','paragraph','heading','text','hardBreak','bulletList','orderedList','listItem','blockquote','horizontalRule','table','tableRow','tableCell','tableHeader','poll']);
export function validDocument(value:unknown):value is RichNode{
 let count=0;const pollIds=new Set<string>();function check(v:unknown,depth:number):boolean{if(!v||typeof v!=='object'||Array.isArray(v)||depth>16||++count>4000)return false;const n=v as RichNode;if(n.type==='poll'){if(depth!==1||!validPoll(n.attrs)||pollIds.has(n.attrs.id)||pollIds.size>=10)return false;pollIds.add(n.attrs.id);return true;}if(!nodes.has(n.type)||n.text!==undefined&&(typeof n.text!=='string'||n.text.length>30000))return false;if(n.attrs&&Object.values(n.attrs).some(x=>typeof x==='object'&&x!==null&&!Array.isArray(x)))return false;if(n.marks&&(!Array.isArray(n.marks)||n.marks.some(m=>!m||!['bold','italic','underline','strike','textStyle'].includes(m.type))))return false;return !n.content||Array.isArray(n.content)&&n.content.every(c=>check(c,depth+1))}return check(value,0)&&(value as RichNode).type==='doc'&&JSON.stringify(value).length<=200000;
}
export function documentText(n:RichNode):string{return n.type==='poll'?String(n.attrs?.question||'Voting'):n.type==='text'?n.text||'':n.type==='hardBreak'?'\n':(n.content||[]).map(documentText).join(['doc','bulletList','orderedList','table','tableRow'].includes(n.type)?'\n':'')}
export function validAnnouncement(b:unknown):b is {title:string;subtitle:string;body:RichNode;attachments?:AnnouncementAttachment[]}{if(!b||typeof b!=='object')return false;const v=b as {title:string;subtitle:string;body:RichNode};return typeof v.title==='string'&&v.title.trim().length>0&&v.title.length<=200&&typeof v.subtitle==='string'&&v.subtitle.length<=500&&validDocument(v.body)}
export function filterAnnouncements(rows:AnnouncementRow[],query:string,period:Period,from:string,to:string,now=new Date()) {const {start,end}=bounds(period,wibDate(now),from,to||from);return rows.filter(r=>!r.deleted_at&&`${r.title} ${r.subtitle} ${r.created_by_name}`.toLowerCase().includes(query.trim().toLowerCase())&&(period==='all'||period==='range'&&!from||new Date(r.created_at)>=start&&new Date(r.created_at)<end)).sort((a,b)=>Number(!!b.is_pinned)-Number(!!a.is_pinned)||b.created_at.localeCompare(a.created_at))}
