export type Consent={patientName:string;dob:string;gender:string;contact:string;emergencyName:string;relationship:string;emergencyContact:string;patientSignature:string;medicSignature:string;witnessSignature:string;date:string;fileNo?:string};
export const consentIntro='I, as the patient hereby give my information consent for medical treatment and procedures to be administered by the healthcare professional at the San Andreas Health Department. I, as the patient understand and acknowledge the following :';
export const consentTerms=[
'Healthcare providers to provide medical treatment, conduct diagnostic tests, and perform necessary procedures to diagnose and treat my medical condition;',
'May employ a variety of medical treatments, including but not limited to examinations, diagnostic tests, medical procedures, surgeries, administration of medication, and the use of medical devices. I understand that alternative treatments, risks, and potential complications will be discussed with me before any procedures are performed;',
'Understand that all medical treatments and procedures carry certain risks and potential benefits;',
'Agree to provide accurate and complete information about my medical history, current medications, allergies, and other relevant details. I understand I should follow any post-treatment instructions and attend follow-up appointments as recommended;',
'Read and understand the contents of this Medical Consent Form, and I voluntarily consent to receive medical treatment and procedures.'];
export function validConsent(d:unknown):d is Consent{if(!d||typeof d!=='object')return false;const v=d as Consent;return ['patientName','dob','gender','contact','emergencyName','relationship','emergencyContact','patientSignature','medicSignature','witnessSignature','date'].every(k=>typeof v[k as keyof Consent]==='string'&&String(v[k as keyof Consent]).length<=200)&&(v.fileNo===undefined||typeof v.fileNo==='string'&&/^\d{3}\/(?:SAHD|(?:I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)\.SAHD)\/\d{4}$/.test(v.fileNo))&&!!v.patientName.trim()&&!!v.emergencyName.trim()&&['Men','Woman'].includes(v.gender)&&/^\d{2}\/\d{2}\/\d{4}$/.test(v.dob)&&!!v.patientSignature.trim()&&!!v.medicSignature.trim()&&!!v.witnessSignature.trim()}

export function consentDate(date:string){const [day,month,year]=date.split('/');const names=['January','February','March','April','May','June','July','August','September','October','November','December'];return `${day} ${names[Number(month)-1]||''} ${year}`}
export function makeConsentFileNo(date:string,serial:number){const year=date.split('/')[2];return `${String(serial).padStart(3,'0')}/SAHD/${year}`}
export function consentFileNo(data:Consent){if(data.fileNo)return data.fileNo.replace(/\/(?:I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)\.SAHD\//,'/SAHD/');let hash=0;for(const char of data.date+data.patientName)hash=(hash*31+char.charCodeAt(0))>>>0;return makeConsentFileNo(data.date,hash%999+1)}
