import 'server-only';import {cookies} from 'next/headers';import {redirect} from 'next/navigation';import {demoAllowed,serverClient} from './supabase/server';
import {demoProfile,demoMembers,demoNotices,demoAppointments,type Profile,type Notice,type Appointment,type Surgery} from './portal-data';
export type Bootstrap={mode:'demo'|'live';profile:Profile;members:Profile[];notices:Notice[];appointments:Appointment[];surgeries:Surgery[];bigFires:Surgery[];announcements:{id:string;title:string;subtitle:string;body:string;publishedAt:string}[];error:string|null};
export async function portalBootstrap():Promise<Bootstrap>{
 const client=await serverClient();const user=client?(await client.auth.getUser()).data.user:null;
 if(!user){if(demoAllowed()&&(await cookies()).get('sahd-demo')?.value==='active')return {mode:'demo',profile:demoProfile,members:demoMembers,notices:demoNotices,appointments:demoAppointments,surgeries:[],bigFires:[],announcements:[{id:'briefing',title:'Briefing tim medis — Jumat, 9 Oktober',subtitle:'Informasi jadwal dan koordinasi terbaru untuk seluruh anggota SAHD.',body:'Briefing tim dijadwalkan pada Jumat pukul 20.00 WIB. Pembahasan meliputi koordinasi pelayanan, penyusunan laporan, serta jadwal consultation.',publishedAt:'2026-10-08T06:30:00Z'}],error:null};redirect('/login')}
 const results=await Promise.all([client!.from('profiles').select('*').eq('id',user.id).single(),client!.from('member_directory').select('*').order('display_name'),client!.from('notifications').select('*').order('created_at',{ascending:false}).limit(50),client!.from('consultations').select('*').is('deleted_at',null).order('created_at',{ascending:false}),reportRows(client!,'medical_reports'),reportRows(client!,'fire_reports'),client!.from('announcements').select('*').eq('status','published').is('deleted_at',null).order('created_at',{ascending:false})]);
 const [own,memberRows,notifications,consultations,medicalReports,fireReports,announcements]=results;const mapProfile=(p:Record<string,unknown>):Profile=>({id:String(p.id),name:String(p.display_name||'Member'),role:String(p.role||'Member'),division:String(p.division||'Belum ditetapkan'),position:String(p.job_title||''),teams:Array.isArray(p.teams)?p.teams.map(String):[],providers:Array.isArray(p.providers)?p.providers.map(String):[],avatar:String(p.avatar_url||''),notifications:p.notifications_enabled!==false});
 const base={id:user.id,display_name:own.data?.display_name||user.user_metadata?.display_name||'Member',role:'Member',division:null,providers:user.identities?.map(i=>i.provider==='email'?'Register':i.provider==='google'?'Google':'Discord')||[]};
 const profile=mapProfile(own.data||base);profile.providers=base.providers;const providerAvatar=user.user_metadata?.avatar_url||user.user_metadata?.picture;if(typeof providerAvatar==='string'&&providerAvatar.startsWith('https://'))profile.avatar=providerAvatar;
 const discordIdentity=user.identities?.find(identity=>identity.provider==='discord');
 if(user.app_metadata?.provider==='discord'||user.identities?.length===1&&discordIdentity){
  const discordData={...user.user_metadata,...discordIdentity?.identity_data};
  const discordName=[discordData.global_name,discordData.full_name,discordData.name,discordData.preferred_username,discordData.user_name].find(value=>typeof value==='string'&&value.trim());
  if(typeof discordName==='string')profile.accountName=discordName.trim();
 }
 const members=(memberRows.data||[]).map(mapProfile);
 const signAvatar=async (profile:Profile,path:string|undefined)=>{if(path){const {data}=await client!.storage.from('avatars').createSignedUrl(path,3600);profile.avatar=data?.signedUrl||profile.avatar}};
 await Promise.all([signAvatar(profile,own.data?.avatar_path),...members.map((m,i)=>signAvatar(m,memberRows.data?.[i]?.avatar_path))]);
 return {mode:'live',profile,members,notices:(notifications.data||[]).map(n=>({id:n.id,title:n.title,body:n.body||'',type:n.is_mentioned?'mention':n.type,href:n.target_path,read:!!n.read_at,at:new Date(n.created_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} as Notice)),appointments:(consultations.data||[]).map(a=>({id:a.id,name:a.name,complaint:a.complaint,doctor:[...(a.mentions?.users||[]).map((id:string)=>members.find(m=>m.id===id)?.name||id),...(a.mentions?.roles||[]),...(a.mentions?.divisions||[])].join(', ')||a.doctor_name||'Belum ditugaskan',date:a.appointment_date,createdAt:a.created_at,status:a.status})),surgeries:(medicalReports.data||[]).map(r=>({id:String(r.id),category:r.category,performedAt:String(r.created_at),status:'completed',final:true} as Surgery)),bigFires:(fireReports.data||[]).filter(r=>r.status==='resolved').map(r=>({id:String(r.id),category:'minor',performedAt:String(r.created_at),status:'completed',final:true} as Surgery)),announcements:(announcements.data||[]).map(a=>({id:a.id,title:a.title,subtitle:a.subtitle||'',body:a.body_text||'',publishedAt:a.published_at})),error:results.some(r=>r.error)?'Sebagian data belum dapat dimuat. Periksa koneksi dan migration database; data contoh tidak digunakan sebagai pengganti.':null};
}

async function reportRows(client:NonNullable<Awaited<ReturnType<typeof serverClient>>>,table:'medical_reports'|'fire_reports'){const rows:Record<string,unknown>[]=[];for(let offset=0;;offset+=1000){const result=await client.from(table).select(table==='medical_reports'?'id,category,created_at':'id,status,created_at').is('deleted_at',null).order('id').range(offset,offset+999);if(result.error)return {data:rows,error:result.error};rows.push(...result.data);if(result.data.length<1000)return {data:rows,error:null}}}
