import type {FireAttachment} from '@/lib/fire-attachments';
import {serverClient,validOrigin} from '@/lib/supabase/server';
import {requestProfile} from '@/lib/server-access';
import {validPlasticDraft,plasticText} from '@/lib/plastic-report';
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(v);
async function sign(c:NonNullable<Awaited<ReturnType<typeof serverClient>>>,row:any){if(row?.draft?.attachments)row.draft.attachments=await Promise.all(row.draft.attachments.map(async(a:FireAttachment)=>a.path?{...a,url:(await c.storage.from('plastic-attachments').createSignedUrl(a.path,3600)).data?.signedUrl}:a));return row}
export async function GET(){const c=await serverClient();if(!c||!(await c.auth.getUser()).data.user)return Response.json({error:'Login diperlukan.'},{status:401});const {data,error}=await c.from('plastic_reports').select('*').is('deleted_at',null).order('created_at',{ascending:false}).limit(1000);return error?Response.json({error:'Report gagal dimuat.'},{status:503}):Response.json({reports:await Promise.all((data||[]).map(row=>sign(c,row)))})}
export async function POST(r:Request){if(!validOrigin(r))return Response.json({error:'Origin tidak valid.'},{status:403});const c=await serverClient(),u=c?(await c.auth.getUser()).data.user:null;if(!c||!u)return Response.json({error:'Login diperlukan.'},{status:401});const p=await requestProfile(c,u.id);if(!p||p.position==='Trainee')return Response.json({error:'Trainee hanya dapat melihat report.'},{status:403});const b=await r.json().catch(()=>null);if(!validPlasticDraft(b?.draft)||b.id&&!uuid(b.id))return Response.json({error:'Isi nama pasien, kondisi, alasan, dan penulis laporan.'},{status:400});const row={title:`Plastic Surgery — ${b.draft.name.trim()}`,draft:{...b.draft,paymentStatus:b.draft.paymentStatus||'unpaid',attachments:(b.draft.attachments||[]).map(({url,...a}:FireAttachment)=>a.kind==='link'?{...a,url}:a)},report_text:plasticText(b.draft),updated_at:new Date().toISOString()};const {data,error}=await (b.id?c.from('plastic_reports').update(row).eq('id',b.id).is('deleted_at',null):c.from('plastic_reports').insert({...row,created_by:u.id,created_by_name:p.name})).select().single();return error?Response.json({error:'Report gagal disimpan.'},{status:400}):Response.json({report:await sign(c,data)})}
export async function PATCH(r:Request){if(!validOrigin(r))return Response.json({error:'Origin tidak valid.'},{status:403});const c=await serverClient(),u=c?(await c.auth.getUser()).data.user:null;if(!c||!u)return Response.json({error:'Login diperlukan.'},{status:401});const p=await requestProfile(c,u.id);if(!p||p.position==='Trainee')return Response.json({error:'Trainee hanya dapat melihat report.'},{status:403});const b=await r.json().catch(()=>null);if(!Array.isArray(b?.ids)||!b.ids.length||b.ids.length>1000||!b.ids.every(uuid))return Response.json({error:'Pilihan tidak valid.'},{status:400});const {error}=await c.rpc('trash_plastic_reports',{report_ids:b.ids});return error?Response.json({error:'Report gagal dihapus sementara.'},{status:400}):Response.json({ok:true})}
