import {serverClient,validOrigin} from '@/lib/supabase/server';
import {validConsultation,validCancellationReason} from '@/lib/consultation';
export async function GET(){const c=await serverClient();if(!c||!(await c.auth.getUser()).data.user)return Response.json({error:'Login diperlukan.'},{status:401});const {data,error}=await c.from('consultations').select('*').is('deleted_at',null).order('created_at',{ascending:false});return error?Response.json({error:'Consultation belum tersedia. Jalankan migration 008.'},{status:503}):Response.json({consultations:data.map(r=>({...r,date:r.appointment_date,dob:r.dob||'',contact:r.contact||'',job:r.job||'',notes:r.notes||'',mentions:r.mentions||{users:[],roles:[],divisions:[]}}))})}
export async function POST(request:Request){if(!validOrigin(request))return Response.json({error:'Origin tidak valid.'},{status:403});const c=await serverClient();const user=c?(await c.auth.getUser()).data.user:null;if(!c||!user)return Response.json({error:'Login diperlukan.'},{status:401});const b=await request.json().catch(()=>null);if(!validConsultation(b))return Response.json({error:'Lengkapi Name, Date, Keluhan dan periksa format tanggal.'},{status:400});const {data:p}=await c.from('profiles').select('division,display_name').eq('id',user.id).single();if(!p?.division)return Response.json({error:'Admin perlu menetapkan divisi akun Anda.'},{status:403});const {data,error}=await c.from('consultations').insert({name:b.name.trim(),dob:b.dob||null,appointment_date:b.date,contact:b.contact,job:b.job,complaint:b.complaint,notes:b.notes,mentions:b.mentions,division:p.division,created_by:user.id,created_by_name:p.display_name}).select().single();return error?Response.json({error:'Consultation gagal disimpan. Periksa migration 008 dan pilihan mention.'},{status:400}):Response.json({consultation:{...data,date:data.appointment_date,dob:data.dob||''}})}

export async function PATCH(request:Request){if(!validOrigin(request))return Response.json({error:'Origin tidak valid.'},{status:403});const c=await serverClient();if(!c||!(await c.auth.getUser()).data.user)return Response.json({error:'Login diperlukan.'},{status:401});const b=await request.json().catch(()=>null);const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 if(b?.action==='trash'){if(!Array.isArray(b.ids)||!b.ids.length||b.ids.length>1000||new Set(b.ids).size!==b.ids.length||b.ids.some((id:unknown)=>typeof id!=='string'||!uuid.test(id)))return Response.json({error:'Pilihan tidak valid.'},{status:400});const {error}=await c.rpc('trash_consultations',{consultation_ids:b.ids});return error?Response.json({error:'Hapus gagal. Pilih data milik Anda dan pastikan migration 009 tersedia.'},{status:403}):Response.json({ok:true})}
 if(typeof b?.id!=='string'||!uuid.test(b.id)||!['done','cancel','edit'].includes(b.action))return Response.json({error:'Action tidak valid.'},{status:400});if(b.action==='edit'&&!validConsultation(b.input))return Response.json({error:'Periksa field wajib dan format tanggal.'},{status:400});if(b.action==='cancel'&&!validCancellationReason(b.reason))return Response.json({error:'Keterangan pembatalan wajib diisi, maksimal 2000 karakter.'},{status:400});const {data,error}=await (b.action==='cancel'?c.rpc('cancel_consultation',{consultation_id:b.id,reason:b.reason.trim()}):b.action==='done'?c.rpc('complete_consultation',{consultation_id:b.id}):c.rpc('edit_consultation',{consultation_id:b.id,input:b.input})).single();const row=data as Record<string,unknown>|null;return error||!row?Response.json({error:'Perubahan gagal. Periksa akses akun, status data, dan migration 009–010.'},{status:403}):Response.json({consultation:{...row,date:row.appointment_date,dob:row.dob||''}})
}
