import {after} from 'next/server';
import {dispatchAnnouncementPush} from '@/lib/announcement-push';
export const maxDuration=60;
import {validAnnouncementAttachments} from '@/lib/announcement-attachments';
import {requestProfile} from '@/lib/server-access';
import {permissions} from '@/lib/access-policy';
import {serverClient,validOrigin} from '@/lib/supabase/server';
import {validAnnouncement,documentText} from '@/lib/announcement';
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
export async function GET(){const c=await serverClient();if(!c||!(await c.auth.getUser()).data.user)return Response.json({error:'Login diperlukan.'},{status:401});const {data,error}=await c.from('announcements').select('*').eq('status','published').is('deleted_at',null).order('is_pinned',{ascending:false}).order('created_at',{ascending:false});if(error)return Response.json({error:'Announcement belum tersedia. Jalankan migration 018.'},{status:503});await Promise.all(data.map(async row=>{await Promise.all((row.attachments||[]).map(async (a:{path?:string;url?:string})=>{if(a.path){const {data:signed}=await c.storage.from('announcement-attachments').createSignedUrl(a.path,3600);a.url=signed?.signedUrl}}))}));return Response.json({announcements:data})}
export async function POST(r:Request){if(!validOrigin(r))return Response.json({error:'Origin tidak valid.'},{status:403});const c=await serverClient();const u=c?(await c.auth.getUser()).data.user:null;if(!c||!u)return Response.json({error:'Login diperlukan.'},{status:401});const actor=await requestProfile(c,(await c.auth.getUser()).data.user!.id);if(!actor||!permissions(actor).announcementWrite)return Response.json({error:'Akses anggota aktif diperlukan.'},{status:403});const b=await r.json().catch(()=>null);if(!validAnnouncement(b)||!validAnnouncementAttachments(b?.attachments||[])||b&&'id' in b&&b.id&&!uuid(b.id))return Response.json({error:'Isi judul announcement dan periksa format konten.'},{status:400});const id='id' in b?b.id:null;const values={title:b.title.trim(),subtitle:b.subtitle.trim(),body_json:b.body,body_text:documentText(b.body),attachments:(b.attachments||[]).map(({url,...a})=>a.kind==='link'?{...a,url}:a)};const {data,error}=await (id?c.from('announcements').update(values).eq('id',id).is('deleted_at',null):c.from('announcements').insert({...values,status:'published',created_by:u.id,published_at:new Date().toISOString()})).select().single();if(!error&&!id)after(()=>dispatchAnnouncementPush());return error?Response.json({error:error.message.includes('Voting that has responses')?'Voting yang sudah memiliki suara tidak dapat diubah atau dihapus.':'Announcement gagal disimpan. Periksa akses dan konfigurasi database.'},{status:403}):Response.json({announcement:data})}
export async function PATCH(r:Request){if(!validOrigin(r))return Response.json({error:'Origin tidak valid.'},{status:403});const c=await serverClient();if(!c||!(await c.auth.getUser()).data.user)return Response.json({error:'Login diperlukan.'},{status:401});const actor=await requestProfile(c,(await c.auth.getUser()).data.user!.id);if(!actor||!permissions(actor).announcementWrite)return Response.json({error:'Akses anggota aktif diperlukan.'},{status:403});const b=await r.json().catch(()=>null);if(b?.action==='pin'){if(!uuid(b.id)||typeof b.pinned!=='boolean')return Response.json({error:'Pilihan pin tidak valid.'},{status:400});const {data,error}=await c.from('announcements').update({is_pinned:b.pinned}).eq('id',b.id).is('deleted_at',null).select('id,is_pinned').single();return error?Response.json({error:'Pin gagal disimpan.'},{status:400}):Response.json({announcement:data})}if(!Array.isArray(b?.ids)||!b.ids.length||b.ids.length>1000||b.ids.some((v:unknown)=>!uuid(v))||new Set(b.ids).size!==b.ids.length)return Response.json({error:'Pilihan tidak valid.'},{status:400});const {error}=await c.rpc('trash_announcements',{item_ids:b.ids});return error?Response.json({error:'Announcement gagal dihapus. Silakan coba kembali.'},{status:403}):Response.json({ok:true})}
